import {describe,expect,it} from "vitest";
import {evaluateSpec,parseDesignApproval,productContentHash} from "../../../src/validation/validate.js";
import {specFixture} from "../spec/fixture.js";
describe("readiness integrity",()=>{
 it("requires AC-linked DoD coverage",()=>{const x=specFixture();x.acceptanceCriteria.push({id:"AC-002",requirementIds:["FR-001"],behavior:"Given a duplicate, when submitted, then the system rejects it"});x.definitionOfDone=[{text:"Done",acceptanceCriteria:["AC-001","AC-999"]},{text:"Again",acceptanceCriteria:["AC-001"]}];expect(evaluateSpec(x).validationFailures.map(f=>f.code)).toEqual(expect.arrayContaining(["dod.unknown","dod.duplicate","dod.coverage"]));});
 it("table-drives every placeholder through all narrative/evidence/provenance/reference categories",()=>{const placeholders=["TBD","TODO","placeholder","lorem ipsum","unknown","later","to be determined","FIXME","XXX"],setters:Array<(x:ReturnType<typeof specFixture>,p:string)=>void>=[
  (x,p)=>{x.specId=p},(x,p)=>{x.pluginVersion=p},(x,p)=>{x.executiveSummary=p},(x,p)=>{x.repositoryContext=p},(x,p)=>{x.targetUser=p},(x,p)=>{x.userProblem=p},(x,p)=>{x.desiredOutcome=p},(x,p)=>{x.proposedSolution=p},(x,p)=>{x.smallestShippableSlice=p},(x,p)=>{x.userStories=[p]},(x,p)=>{x.functionalRequirements[0]!.text=p},(x,p)=>{x.functionalRequirements[0]!.sources=[p]},(x,p)=>{x.acceptanceCriteria[0]!.behavior=`Given input, when used, then displays ${p}`},(x,p)=>{x.uxExpectations=p},(x,p)=>{x.businessRules=[p]},(x,p)=>{x.edgeCases=[p]},(x,p)=>{x.nonFunctionalExpectations=[p]},(x,p)=>{x.existingBehaviorToPreserve=[p]},(x,p)=>{x.nonGoals=[p]},(x,p)=>{x.futureConsiderations=[p]},(x,p)=>{x.dependenciesAndConstraints=[p]},(x,p)=>{x.definitionOfDone=[{text:p,acceptanceCriteria:["AC-001"]}]},(x,p)=>{x.handoffInstructions=p},(x,p)=>{x.evidence.facts[0]!.statement=p},(x,p)=>{x.evidence.inferences=[{statement:p}]},(x,p)=>{x.evidence.assumptions=[{statement:p}]},(x,p)=>{x.evidence.unresolved=[{statement:p}]},(x,p)=>{x.evidence.facts[0]!.sources=[p]},(x,p)=>{x.hostIdentifier=p},(x,p)=>{x.requestedBy=p},(x,p)=>{x.pm={agent:p,model:"model"}},(x,p)=>{x.pm={agent:"agent",model:p}},(x,p)=>{x.additionalSections=[{id:"audit",title:"Audit",body:p}]},(x,p)=>{x.additionalSections=[{id:p,title:"Audit",body:"Evidence"}]}
 ];for(const set of setters)for(const placeholder of placeholders){const x=specFixture();set(x,placeholder);const result=evaluateSpec(x);expect(result.status).toBe("Draft");expect(result.handoffEligible).toBe(false);}});
 it("rejects placeholders in raw design approval identity, reviewer and evidence",()=>{for(const field of ["specId","id","name","role","evidence"]){const x=specFixture(),approval:any={schemaVersion:"1.0.0",specId:x.specId,revision:x.revision,productContentHash:productContentHash(x),decision:"approved",reviewer:{id:"designer",name:"Designer",role:"reviewer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review"};if(field==="specId"||field==="evidence")approval[field]="TBD";else approval.reviewer[field]="TBD";expect(parseDesignApproval(approval,x)).toBeUndefined();}});
});
