import { describe,expect,it } from "vitest";
import { designApprovalSchema,evaluatedSpecSchema,handoffSchema,manifestSchema,productSpecInputSchema } from "../../../src/validation/schemas.js";
import { evaluateSpec,productContentHash } from "../../../src/validation/validate.js";
import { renderSpec,artifactManifest } from "../../../src/spec/render.js";
import { specFixture } from "../spec/fixture.js";
import { SPEC_FORMATS, SPEC_LIMITS } from "../../../src/spec/limits.js";
describe("strict runtime schema parity",()=>{
  it("accepts complete runtime contracts",()=>{const input=specFixture(),evaluated=evaluateSpec(input),rendered=renderSpec(evaluated);expect(productSpecInputSchema.safeParse(input).success).toBe(true);expect(evaluatedSpecSchema.safeParse(evaluated).success).toBe(true);expect(handoffSchema.safeParse(JSON.parse(rendered.handoffJson)).success).toBe(true);expect(manifestSchema.safeParse(JSON.parse(artifactManifest(evaluated,rendered))).success).toBe(true);expect(designApprovalSchema.safeParse({schemaVersion:"1.0.0",specId:input.specId,revision:input.revision,productContentHash:productContentHash(input),decision:"approved",reviewer:{id:"human",name:"Human"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review"}).success).toBe(true);});
  it("rejects unknown, missing, wrong-type and conflicting approval hash fields",()=>{const input:any=specFixture();input.unknown=true;expect(productSpecInputSchema.safeParse(input).success).toBe(false);delete input.unknown;delete input.title;expect(productSpecInputSchema.safeParse(input).success).toBe(false);expect(handoffSchema.safeParse({schemaVersion:"1.0.0"}).success).toBe(false);expect(manifestSchema.safeParse({committed:"true"}).success).toBe(false);expect(designApprovalSchema.safeParse({canonicalContentHash:"0".repeat(64)}).success).toBe(false);});
  it("rejects oversized strings, arrays and malformed date-time",()=>{const long=specFixture();long.title="x".repeat(20_001);expect(productSpecInputSchema.safeParse(long).success).toBe(false);const many=specFixture();many.userStories=Array(201).fill("story");expect(productSpecInputSchema.safeParse(many).success).toBe(false);const date=specFixture();date.generatedAt="July 18";expect(productSpecInputSchema.safeParse(date).success).toBe(false);});
  it("exports immutable shared bounds and strict formats for runtime mirroring",()=>{expect(Object.isFrozen(SPEC_LIMITS)).toBe(true);expect(Object.isFrozen(SPEC_FORMATS)).toBe(true);expect(SPEC_LIMITS).toMatchObject({string:20000,requirements:500,criteria:1000,evidencePerGroup:500,priorDepth:20});expect(SPEC_FORMATS.functionalRequirementId.test("FR-001")).toBe(true);expect(SPEC_FORMATS.safeReference.test("../secret")).toBe(false);const invalid=specFixture();invalid.hostIdentifier="../host";expect(productSpecInputSchema.safeParse(invalid).success).toBe(false);});
});
