import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path";
import { describe, expect, it } from "vitest";
import { loadConfig } from "../../../src/config/index.js";
async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), "spm-config-")); const home = path.join(root, "home"); const project = path.join(root, "project"); await mkdir(home); await mkdir(project); return { root, home, project }; }
async function put(file: string, value: unknown) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify(value)); }
describe("trusted configuration", () => {
  it("provides immutable deny-only safe defaults", async () => { const f = await fixture(); const value = await loadConfig({ projectRoot: f.project, homeDir: f.home, env: {} }); expect(value.allow_external_research).toBe(false); expect(value.denied_permissions).toEqual({edit:"deny",bash:"deny",task:"deny"}); expect(value.tool_restrictions).toContain("bash"); expect(value.required_specification_sections).toHaveLength(23); });
  it("applies precedence while project cannot widen capabilities", async () => { const f = await fixture(); await put(path.join(f.home, ".config/opencode/senior-pm.json"), { senior_pm: { allow_repository_history: true, context_limits: { max_files: 90 } } }); await put(path.join(f.project, ".opencode/senior-pm.jsonc"), { senior_pm: { allow_external_research: true, context_limits: { max_files: 120 }, required_specification_sections: ["project-extra"] } }); const value = await loadConfig({ projectRoot: f.project, homeDir: f.home, env: { SENIOR_PM_CONFIG_JSON: '{"senior_pm":{"effort":"high","invocation_target":"exact-agent","allow_programmatic_invocation":true}}' } }); expect(value.invocation_target).toBe("exact-agent"); expect(value.allow_repository_history).toBe(true); expect(value.allow_external_research).toBe(false); expect(value.context_limits?.max_files).toBe(90); });
  it("rejects project/tuple invocation targets and arbitrary permission syntax", async () => { const f=await fixture(); await put(path.join(f.project,".opencode/senior-pm.json"),{senior_pm:{invocation_target:"attacker"}}); await expect(loadConfig({projectRoot:f.project,homeDir:f.home,env:{}})).rejects.toThrow(/operator-only/); const tuple=await fixture(); await expect(loadConfig({projectRoot:tuple.project,homeDir:tuple.home,env:{},tupleOptions:{senior_pm:{allow_programmatic_invocation:true}}})).rejects.toThrow(/operator-only/); const syntax=await fixture(); await expect(loadConfig({projectRoot:syntax.project,homeDir:syntax.home,env:{SENIOR_PM_CONFIG_JSON:'{"senior_pm":{"permission_restrictions":["edit:allow"]}}'}})).rejects.toThrow(/Unrecognized key/); });
  it("accepts JSONC and reports invalid settings clearly", async () => { const f = await fixture(); const file = path.join(f.project, ".opencode/senior-pm.jsonc"); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, '{ // safe\n "senior_pm": {"mode":"wrong",},}'); await expect(loadConfig({ projectRoot: f.project, homeDir: f.home, env: {} })).rejects.toThrow(/mode.*Invalid enum value/); });
  it("allows project false to tighten invocation",async()=>{const f=await fixture();await put(path.join(f.home,".config/opencode/senior-pm.json"),{senior_pm:{allow_programmatic_invocation:true,invocation_target:"operator-agent"}});await put(path.join(f.project,".opencode/senior-pm.json"),{senior_pm:{allow_programmatic_invocation:false}});const value=await loadConfig({projectRoot:f.project,homeDir:f.home,env:{}});expect(value.allow_programmatic_invocation).toBe(false);expect(value.invocation_target).toBe("operator-agent");});
  it("rejects oversized and deeply structured configuration",async()=>{const f=await fixture();await expect(loadConfig({projectRoot:f.project,homeDir:f.home,env:{SENIOR_PM_CONFIG_JSON:" ".repeat(1_000_001)}})).rejects.toThrow(/exceeds/);await expect(loadConfig({projectRoot:f.project,homeDir:f.home,env:{SENIOR_PM_CONFIG_JSON:JSON.stringify({senior_pm:{adapter_metadata:{deep:{nested:true}}}})}})).rejects.toThrow();});
  it("stats oversized files before allocating or reading",async()=>{const f=await fixture();let read=false,closed=false;const fake={stat:async()=>({isFile:()=>true,size:1_000_001}),read:async()=>{read=true;return{bytesRead:0}},close:async()=>{closed=true}} as any;await expect(loadConfig({projectRoot:f.project,homeDir:f.home,env:{SENIOR_PM_CONFIG:"oversized.json"},openFile:async()=>fake})).rejects.toThrow(/exceeds/);expect(read).toBe(false);expect(closed).toBe(true);});
});
