import { mkdtemp, mkdir, rename, symlink, writeFile } from "node:fs/promises"; import os from "node:os"; import path from "node:path";
import { describe, expect, it } from "vitest"; import { discoverRepository } from "../../../src/repository/index.js";
async function repo(files: Record<string,string>) { const root = await mkdtemp(path.join(os.tmpdir(), "spm-repo-")); for (const [name, body] of Object.entries(files)) { const file = path.join(root, name); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, body); } return root; }
describe("bounded repository discovery", () => {
  it.each([
    ["web", { "package.json": '{"scripts":{"serve":"x"}}', "src/components/card.ts": "export const Card = 'catalog'", "README.md": "A sample storefront" }],
    ["api", { "go.mod": "module example.invalid/service", "routes.go": "package service\n// health endpoint" }],
    ["cli", { "Cargo.toml": "[package]\nname='toolbox'", "src/main.rs": "fn main() {}", "tests/run.rs": "test command" }],
    ["empty", {}]
  ])("normalizes a generic %s repository", async (_shape, files) => { const context = await discoverRepository(await repo(files)); expect(context.hostIdentifier).toBeTruthy(); expect(context.evidence).toBeInstanceOf(Array); if (!Object.keys(files).length) expect(context.missingContext).toContain("No recognized manifest discovered."); });
  it("excludes sensitive, binary, vendor, symlink and outside content", async () => { const outside = await repo({ "outside.txt": "must-not-leak" }); const root = await repo({ ".env": "TOKEN=secret", "node_modules/pkg/index.js": "vendor leak", "image.png": "\0binary", "safe.txt": "Authorization: bearer-value" }); await symlink(path.join(outside, "outside.txt"), path.join(root, "link.txt")); const context = await discoverRepository(root); const joined = JSON.stringify(context); expect(joined).not.toContain("must-not-leak"); expect(joined).not.toContain("vendor leak"); expect(joined).not.toContain("bearer-value"); expect(joined).toContain("[REDACTED]"); });
  it("enforces file and byte limits", async () => { const root = await repo({ "a.txt": "a".repeat(100), "b.txt": "b".repeat(100) }); const context = await discoverRepository(root, { limits: { maxFiles: 1, maxFileBytes: 10, maxTotalBytes: 10 } }); expect(context.evidence).toHaveLength(1); expect(context.evidence[0]!.excerpt.length).toBeLessThanOrEqual(10); expect(context.missingContext.join(" ")).toMatch(/resource limit/); });
  it("does not return history without both authorization flags", async () => { const root = await repo({ "README.md": "history-free" }); expect((await discoverRepository(root, { allowHistory: true })).history).toEqual([]); });
  it("returns by the deadline when an individual operation stalls", async () => { const root=await repo({"safe.txt":"safe"}); const started=Date.now(); const context=await discoverRepository(root,{limits:{timeoutMs:20},fs:{readdir:(async()=>new Promise(()=>{})) as any}}); expect(Date.now()-started).toBeLessThan(500); expect(context.missingContext.join(" ")).toMatch(/deadline/); });
  it("continues after a racy/unreadable file without returning outside content", async () => { const root=await repo({"a.txt":"safe-a","b.txt":"safe-b"}); let calls=0; const context=await discoverRepository(root,{fs:{realpath:(async (p:any)=>{ calls++; if(String(p).endsWith("a.txt")) throw Object.assign(new Error("changed"),{code:"ENOENT"}); return (await import("node:fs/promises")).realpath(p); }) as any}}); expect(JSON.stringify(context)).not.toContain("outside-secret"); expect(context.evidence.some(x=>x.excerpt.includes("safe-b"))).toBe(true); expect(context.missingContext.join(" ")).toMatch(/changed/); expect(calls).toBeGreaterThan(1); });
  it("rejects expected-path versus opened-fd mismatch before returning bytes",async()=>{const root=await repo({"safe.txt":"outside-secret"});const context=await discoverRepository(root,{descriptorTarget:async()=>"/tmp/outside.txt"});expect(JSON.stringify(context)).not.toContain("outside-secret");expect(context.missingContext.join(" ")).toMatch(/changed/);});
  it("skips every excerpt when descriptor targets are unsupported",async()=>{const root=await repo({"safe.txt":"must-not-return"});const context=await discoverRepository(root,{platform:"darwin"});expect(context.evidence).toEqual([]);expect(JSON.stringify(context)).not.toContain("must-not-return");expect(context.containmentGuarantee).toBe("unsupported-content-skipped");});
  it("runs history only through held root/.git descriptors with sanitized env",async()=>{const root=await repo({"README.md":"safe"}),git=path.join(root,".git");await mkdir(git);let received="";const context=await discoverRepository(root,{allowHistory:true,historyAuthorized:true,historyRunner:async(descriptorRoot,descriptorGit,_timeout,env)=>{received=descriptorRoot;expect(await (await import("node:fs/promises")).realpath(descriptorRoot)).toBe(root);expect(await (await import("node:fs/promises")).realpath(descriptorGit)).toBe(git);expect(Object.keys(env).every(k=>["PATH","LANG","LC_ALL"].includes(k))).toBe(true);return "abc123 secure history";}});expect(received).toMatch(new RegExp(`^/proc/${process.pid}/fd/\\d+$`));expect(context.history).toEqual(["abc123 secure history"]);});
  it("skips .git file indirection",async()=>{const root=await repo({".git":"gitdir: /tmp/outside","README.md":"safe"});let called=false;const context=await discoverRepository(root,{allowHistory:true,historyAuthorized:true,historyRunner:async()=>{called=true;return"leak"}});expect(called).toBe(false);expect(context.history).toEqual([]);});
  it("fails closed when .git is replaced after descriptor preflight",async()=>{const root=await repo({"README.md":"safe"}),git=path.join(root,".git");await mkdir(git);let swapped=false,called=false;const native=await import("node:fs/promises");const context=await discoverRepository(root,{allowHistory:true,historyAuthorized:true,descriptorTarget:async fd=>{const target=await native.realpath(`/proc/self/fd/${fd}`);if(target===git&&!swapped){swapped=true;await rename(git,`${git}-old`);await mkdir(git);}return target},historyRunner:async()=>{called=true;return"leak"}});expect(called).toBe(false);expect(context.history).toEqual([]);expect(context.missingContext.join(" ")).toMatch(/history skipped/i);});
  it("returns bounded safe detail and excludes nested credentials",async()=>{const root=await repo({"src/detail.txt":"database postgres://user:pass@host/db\nAKIA0000000000000000\nBearer invalid.synthetic.value","config/secrets.yml":"must-not-leak",".aws/credentials":"must-not-leak-either"});const context=await discoverRepository(root,{detailPaths:["src/detail.txt","config/secrets.yml"]});const detail=context.evidence.find(x=>x.path==="src/detail.txt");expect(detail?.category).toBe("detail");expect(detail?.excerpt).toContain("[REDACTED DATABASE URL]");expect(JSON.stringify(context)).not.toContain("must-not-leak");expect(context.missingContext.join(" ")).toContain("config/secrets.yml");});
  it("skips history where descriptor containment is unsupported",async()=>{const root=await repo({"README.md":"safe"});let called=false;const context=await discoverRepository(root,{platform:"darwin",allowHistory:true,historyAuthorized:true,historyRunner:async()=>{called=true;return "leak";}});expect(called).toBe(false);expect(context.history).toEqual([]);expect(context.missingContext.join(" ")).toMatch(/history skipped/i);});
});
