import { access, mkdtemp, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createSeniorPMRuntime as createRuntime } from "../../../src/plugin/runtime.js";
import { bundledAssetText, loadAsset } from "../../../src/plugin/assets.js";
import { SeniorPMConfigurationError } from "../../../src/plugin/errors.js";
async function root(config?: unknown) { const r = await mkdtemp(path.join(os.tmpdir(), "spm-plugin-")); if (config) { await mkdir(path.join(r, ".opencode")); await writeFile(path.join(r, ".opencode/senior-pm.json"), JSON.stringify(config)); } return r; }
const parsed=(value:any)=>JSON.parse(typeof value==="string"?value:value.output);
function input(r: string, client: any = {}) { return { client, project: {}, directory: r, worktree: r, serverUrl: new URL("http://localhost"), experimental_workspace: { register() {} }, $: {} } as any; }
const active: Array<Awaited<ReturnType<typeof createRuntime>>> = [];
async function createSeniorPMRuntime(...args: Parameters<typeof createRuntime>):Promise<any> { const hooks=await createRuntime(...args); active.push(hooks); return hooks; }
afterEach(async()=>{for(const hooks of active.splice(0))await hooks.dispose?.();});
describe("standard runtime", () => {
  it("loads exact bundled canonical assets and safe frontmatter", async () => { const asset = await loadAsset("agents/senior-pm.md"),source=await readFile(new URL("../../../assets/agents/senior-pm.md",import.meta.url),"utf8");expect(bundledAssetText("agents/senior-pm.md")).toBe(source.replace(/\r\n?/g,"\n"));expect(asset.raw).toBe(source.replace(/\r\n?/g,"\n")); expect(asset.frontmatter.mode).toBe("subagent"); expect(asset.body).toContain("# Senior Product Manager"); });
  it("registers exact IDs, bindings, assets and deny-first permissions", async () => { const r = await root(); const hooks = await createSeniorPMRuntime(input(r)); const config: any = {}; await hooks.config!(config); expect(Object.keys(hooks.tool!)).toEqual(["senior_pm_config", "senior_pm_discover", "senior_pm_write_spec", "senior_pm_validate_spec", "senior_pm_handoff"]); expect(Object.keys(config.command)).toEqual(["pm-spec", "pm-revise", "pm-validate", "pm-handoff"]); expect(config.agent["senior-pm"].prompt).toBe((await loadAsset("agents/senior-pm.md")).body); expect(config.agent["senior-pm"].model).toBeUndefined(); expect(config.agent["senior-pm"].permission).toMatchObject({ "*": "deny", external_directory: "deny", read: "deny", grep: "deny", glob: "deny", list: "deny", edit: "deny", bash: "deny", task: "deny", senior_pm_handoff: "ask",senior_pm_approval_sidecar:"ask" }); for (const command of Object.values<any>(config.command)) expect(command).toMatchObject({ agent: "senior-pm", subtask: true }); });
  it("refuses agent and command collisions", async () => { const hooks = await createSeniorPMRuntime(input(await root())); await expect(hooks.config!({ agent: { "senior-pm": {} } } as any)).rejects.toBeInstanceOf(SeniorPMConfigurationError); const other = await createSeniorPMRuntime(input(await root())); await expect(other.config!({ command: { "pm-spec": {} } } as any)).rejects.toThrow(/Command collision/); });
  it("registers nothing when disabled", async () => { const hooks = await createSeniorPMRuntime(input(await root({ senior_pm: { enabled: false } }))); expect(hooks).toEqual({}); });
  it("only operator-authorized research adds web read tools", async () => { const project = await root({ senior_pm: { allow_external_research: true } }); const projectHooks = await createSeniorPMRuntime(input(project)); const a: any = {}; await projectHooks.config!(a); expect(a.agent["senior-pm"].permission.webfetch).toBeUndefined(); });
  it("keeps command authorization server-side and inserts no bearer text", async () => { const hooks = await createSeniorPMRuntime(input(await root())); const output: any = { parts: [] }; await hooks["command.execute.before"]!({ command: "pm-handoff", sessionID: "s", arguments: "--artifact-base sample.r001 --target engineer" }, output); expect(output.parts).toEqual([]); });
  it("preserves an explicit handoff deny", async () => { const r = await root({ senior_pm: { denied_permissions: { senior_pm_handoff: "deny" } } }); const hooks = await createSeniorPMRuntime(input(r)); const config: any = {}; await hooks.config!(config); expect(config.agent["senior-pm"].permission.senior_pm_handoff).toBe("deny"); });
  it("preserves an explicit approval-sidecar deny over the default ask",async()=>{const r=await root({senior_pm:{denied_permissions:{senior_pm_approval_sidecar:"deny"}}}),hooks=await createSeniorPMRuntime(input(r)),config:any={};await hooks.config!(config);expect(config.agent["senior-pm"].permission.senior_pm_approval_sidecar).toBe("deny");});
  it("falls back from filesystem-root worktree to the writable non-Git directory and loads project policy",async()=>{const r=await root({senior_pm:{specification_directory:"product/senior-pm"}}),hooks=await createSeniorPMRuntime({...input(r),worktree:path.parse(r).root} as any),ctx:any={sessionID:"s",messageID:"m",agent:"senior-pm",directory:r,worktree:"/",abort:new AbortController().signal,metadata(){},ask:async()=>{}};const configured=JSON.parse(await hooks.tool!.senior_pm_config!.execute({},ctx));expect(configured.outputRoot).toBe("product/senior-pm");const draft:any={schemaVersion:"1.0.0",pluginVersion:"0.1.0",specId:"SPEC-ROOT",slug:"root-selection",revision:1,generatedAt:"2026-07-18T12:00:00.000Z",title:"Root selection",hostIdentifier:"host",requestedBy:"owner",pm:{agent:"senior-pm"},executiveSummary:"Select a safe project root.",repositoryContext:"A non-Git project.",targetUser:"Operators",userProblem:"Writes target the wrong root.",desiredOutcome:"Writes stay in the project.",proposedSolution:"Select the active directory.",smallestShippableSlice:"Select one root.",userStories:["As an operator, writes stay local."],functionalRequirements:[{id:"FR-001",text:"Use project root"}],acceptanceCriteria:[{id:"AC-001",requirementIds:["FR-001"],behavior:"Given a non-Git directory, when writing, then files stay local"}],uxExpectations:"None",businessRules:["Stay contained"],edgeCases:["Filesystem root hint"],nonFunctionalExpectations:["No root writes"],existingBehaviorToPreserve:["Git root selection"],nonGoals:["Git initialization"],futureConsiderations:["Worktrees"],dependenciesAndConstraints:["Writable project"],definitionOfDone:[{text:"AC-001 passes",acceptanceCriteria:["AC-001"]}],handoffInstructions:"Validate root.",evidence:{facts:[],inferences:[],assumptions:[],unresolved:[]},interfaceImpact:"none",technicalPlanningRequired:true};const written=JSON.parse(await hooks.tool!.senior_pm_write_spec!.execute({input:draft},ctx));expect(written.outputRoot).toBe("product/senior-pm");expect(JSON.parse(await hooks.tool!.senior_pm_validate_spec!.execute({artifactBase:written.artifactBase},ctx)).valid).toBe(true);await expect(access(path.join(path.parse(r).root,"product/senior-pm",`${written.artifactBase}.json`))).rejects.toThrow();});
  it("selects a verified containing Git root for a nested directory",async()=>{const git=await root({senior_pm:{specification_directory:"git-output/senior-pm"}});await mkdir(path.join(git,".git"));const nested=path.join(git,"packages/app");await mkdir(nested,{recursive:true});const hooks=await createSeniorPMRuntime({...input(nested),worktree:git} as any),ctx:any={sessionID:"s",messageID:"m",agent:"senior-pm",directory:nested,worktree:git,abort:new AbortController().signal,metadata(){},ask:async()=>{}};const configured=JSON.parse(await hooks.tool!.senior_pm_config!.execute({},ctx));expect(configured.outputRoot).toBe("git-output/senior-pm");});
  it("rejects unrelated context directories and conflicting verified Git hints",async()=>{const r=await root(),other=await root(),malicious=await root();await mkdir(path.join(malicious,".git"));const hooks=await createSeniorPMRuntime(input(r)),base:any={sessionID:"s",messageID:"m",agent:"senior-pm",abort:new AbortController().signal,metadata(){},ask:async()=>{}};await expect(hooks.tool!.senior_pm_config!.execute({}, {...base,directory:other,worktree:"/"})).rejects.toThrow(/outside pinned host root/);await expect(hooks.tool!.senior_pm_discover!.execute({}, {...base,directory:r,worktree:malicious})).rejects.toThrow(/does not match pinned host root/);});
  it("holds a lifetime root descriptor and fails closed after pathname replacement",async()=>{const r=await root(),hooks=await createSeniorPMRuntime(input(r));expect(hooks.dispose).toBeTypeOf("function");await rename(r,`${r}-original`);await mkdir(r);const context:any={sessionID:"s",messageID:"m",agent:"senior-pm",directory:r,worktree:r,abort:new AbortController().signal,metadata(){},ask:async()=>{}};await expect(hooks.tool!.senior_pm_config!.execute({},context)).rejects.toThrow(/pathname changed/);});
});
