import { mkdtemp, mkdir, rename, stat, writeFile } from "node:fs/promises"; import os from "node:os"; import path from "node:path";
import { describe, expect, it } from "vitest";
import { DEFAULT_SETTINGS } from "../../../src/config/schema.js";
import { createRuntimeTools, productSpecInputSchema } from "../../../src/tools/runtime.js";
import { SPEC_LIMITS } from "../../../src/spec/limits.js";
import { PinnedRepositoryRoot } from "../../../src/shared/secure-fs.js";
import { HandoffNonceStore } from "../../../src/workflow/nonce.js";
import { specFixture } from "../spec/fixture.js";
import { productContentHash } from "../../../src/validation/validate.js";
const context = (root: string, sessionID = "session") => ({ sessionID, messageID: "message", agent: "senior-pm", directory: root, worktree: root, abort: new AbortController().signal, metadata() {}, async ask() {} });
async function runtime(settings: any = {}, client: any = {}) { const root = await mkdtemp(path.join(os.tmpdir(), "spm-tools-")), identity=await stat(root); return { root, tools: createRuntimeTools({ root, rootIdentity:{dev:identity.dev,ino:identity.ino}, settings: { ...structuredClone(DEFAULT_SETTINGS), ...settings }, client, nonce: new HandoffNonceStore(), hostConfig: {} }) }; }
describe("tool boundaries", () => {
  it("returns sanitized config without environment values or paths", async () => { const { tools, root } = await runtime(); const output = await tools.senior_pm_config.execute({}, context(root)); expect(output).toContain('"pluginVersion"'); expect(output).not.toContain("SENIOR_PM_CONFIG_JSON"); expect(output).not.toContain(os.homedir()); });
  it("discovers only the pinned repository", async () => { const { tools, root } = await runtime(); await writeFile(path.join(root, "README.md"), "A neutral utility"); const output = await tools.senior_pm_discover.execute({}, context(root)); expect(output).toContain("README.md"); await expect(tools.senior_pm_discover.execute({}, context(await mkdtemp(path.join(os.tmpdir(), "other-"))))).rejects.toThrow(/pinned/); });
  it("writes only immutable specification artifacts and validates them", async () => { const { tools, root } = await runtime(); const input = specFixture(); const written = JSON.parse(await tools.senior_pm_write_spec.execute({ input }, context(root)) as string); expect(written.paths.every((p: string) => p.includes(".opencode/specs/senior-pm"))).toBe(true); expect(written.status).toBe("Ready for technical planning"); expect(written.implementationMayBegin).toBe(false); const checked = JSON.parse(await tools.senior_pm_validate_spec.execute({ artifactBase: written.artifactBase }, context(root)) as string); expect(checked,JSON.stringify(checked)).toMatchObject({valid:true}); });
  it("requires a valid eligible committed artifact before manual guidance", async () => { let invoked = false; const {root,tools}=await runtime({}, { session: { create: async () => { invoked = true; } } }); const refused=JSON.parse(await tools.senior_pm_handoff.execute({artifactBase:"missing.r001"},context(root)) as string);expect(refused.mode).toBe("refused");expect(refused.implementationMayBegin).toBe(false);const input=specFixture();const written=JSON.parse(await tools.senior_pm_write_spec.execute({input},context(root)) as string);const manual=JSON.parse(await tools.senior_pm_handoff.execute({artifactBase:written.artifactBase},context(root)) as string);expect(manual.mode).toBe("manual");expect(manual.status).toBe("Ready for technical planning");expect(manual.productHash).toMatch(/^[a-f0-9]{64}$/);expect(invoked).toBe(false); });
  it("does not expose raw design approvals in PM tool schemas",async()=>{const {tools}=await runtime();expect(Object.keys(tools.senior_pm_write_spec.args)).toEqual(["input","approvalSidecar","priorArtifact"]);expect(Object.keys(tools.senior_pm_validate_spec.args)).toEqual(["input","artifactBase"]);});
  it("accepts canonical additionalSections and rejects extraSections",async()=>{const {tools,root}=await runtime(),input=specFixture();input.additionalSections=[{id:"operations",title:"Operations",body:"Operators can inspect recovery records."}];expect(JSON.parse(await tools.senior_pm_validate_spec.execute({input},context(root)) as string).additionalSections).toEqual(input.additionalSections);await expect(tools.senior_pm_validate_spec.execute({input:{...input,extraSections:[{title:"Wrong",body:"Wrong"}]}} as any,context(root))).rejects.toThrow();});
  it("mirrors canonical format and size limits in the OpenCode schema",()=>{const input=specFixture();expect(productSpecInputSchema.safeParse(input).success).toBe(true);expect(productSpecInputSchema.safeParse({...input,generatedAt:"not-a-date"}).success).toBe(false);expect(productSpecInputSchema.safeParse({...input,title:"x".repeat(SPEC_LIMITS.string+1)}).success).toBe(false);expect(productSpecInputSchema.safeParse({...input,functionalRequirements:Array(SPEC_LIMITS.requirements+1).fill(input.functionalRequirements[0])}).success).toBe(false);});
  it("mirrors provenance, source, sidecar, artifact and target formats",async()=>{const input=specFixture();for(const [field,value] of [["hostIdentifier","bad\nvalue"],["requestedBy","bad\0value"]] as const)expect(productSpecInputSchema.safeParse({...input,[field]:value}).success).toBe(false);expect(productSpecInputSchema.safeParse({...input,evidence:{...input.evidence,facts:[{statement:"fact",sources:["../secret"]}]}}).success).toBe(false);const {tools}=await runtime();expect((tools.senior_pm_write_spec.args as any).approvalSidecar.safeParse("../review.json").success).toBe(false);expect((tools.senior_pm_write_spec.args as any).approvalSidecar.safeParse("x".repeat(SPEC_LIMITS.path)+".json").success).toBe(false);expect((tools.senior_pm_validate_spec.args as any).artifactBase.safeParse("bad").success).toBe(false);expect((tools.senior_pm_handoff.args as any).target.safeParse("bad\nagent").success).toBe(false);});
  it("asks for exact approval path/hash/spec/revision and rejects replacement",async()=>{const {tools,root}=await runtime(),first=specFixture();first.interfaceImpact="substantial_ui";await tools.senior_pm_write_spec.execute({input:first},context(root));const second=specFixture();second.revision=2;second.interfaceImpact="substantial_ui";const sidecar=path.join(root,".opencode/specs/senior-pm/review.json"),approval={schemaVersion:"1.0.0",specId:second.specId,revision:2,productContentHash:productContentHash(second),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review/2"};await writeFile(sidecar,JSON.stringify(approval));let asked:any;const authorized={...context(root),ask:async(value:any)=>{asked=value}};const written=JSON.parse(await tools.senior_pm_write_spec.execute({input:second,approvalSidecar:"review.json"},authorized) as string);expect(asked.permission).toBe("senior_pm_approval_sidecar");expect(asked.patterns[0]).toMatch(/^review\.json#sha256=[a-f0-9]{64};spec=SPEC-1;revision=2;product=[a-f0-9]{64}$/);expect(asked.metadata).toMatchObject({path:"review.json",specId:"SPEC-1",revision:2,productContentHash:approval.productContentHash});expect(written.status).toBe("Ready for technical planning");const third=specFixture();third.revision=3;third.interfaceImpact="substantial_ui";const thirdApproval={...approval,revision:3,productContentHash:productContentHash(third)};await writeFile(sidecar,JSON.stringify(thirdApproval));await expect(tools.senior_pm_write_spec.execute({input:third,approvalSidecar:"review.json"},{...context(root),ask:async()=>{await writeFile(sidecar,"{}")}})).rejects.toThrow(/changed after user authorization|schema invalid/);});
  it("fails closed when approval ask is unavailable",async()=>{const {tools,root}=await runtime(),first=specFixture();first.interfaceImpact="substantial_ui";await tools.senior_pm_write_spec.execute({input:first},context(root));const second=specFixture();second.revision=2;second.interfaceImpact="substantial_ui";const approval={schemaVersion:"1.0.0",specId:second.specId,revision:2,productContentHash:productContentHash(second),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review/2"};await writeFile(path.join(root,".opencode/specs/senior-pm/review.json"),JSON.stringify(approval));await expect(tools.senior_pm_write_spec.execute({input:second,approvalSidecar:"review.json"},{...context(root),ask:undefined} as any)).rejects.toThrow(/requires user authorization/);});
  it("rejects approval identity mismatch before asking",async()=>{const {tools,root}=await runtime(),first=specFixture();first.interfaceImpact="substantial_ui";await tools.senior_pm_write_spec.execute({input:first},context(root));const second=specFixture();second.revision=2;second.interfaceImpact="substantial_ui";await writeFile(path.join(root,".opencode/specs/senior-pm/review.json"),JSON.stringify({schemaVersion:"1.0.0",specId:"OTHER",revision:2,productContentHash:productContentHash(second),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review"}));let asked=false;await expect(tools.senior_pm_write_spec.execute({input:second,approvalSidecar:"review.json"},{...context(root),ask:async()=>{asked=true}})).rejects.toThrow(/identity does not match/);expect(asked).toBe(false);});
  it.each([["Draft",(x:any)=>x.userProblem=""],["Ready for design review",(x:any)=>x.interfaceImpact="substantial_ui"]])("refuses %s artifacts",async(status,mutate)=>{const {root,tools}=await runtime();const input=specFixture();mutate(input);const written=JSON.parse(await tools.senior_pm_write_spec.execute({input},context(root)) as string);expect(written.status).toBe(status);const handoff=JSON.parse(await tools.senior_pm_handoff.execute({artifactBase:written.artifactBase},context(root)) as string);expect(handoff.mode).toBe("refused");expect(handoff.implementationMayBegin).toBe(false);});
  it("fails closed when the pinned root is replaced",async()=>{const {root,tools}=await runtime();await rename(root,`${root}-old`);await mkdir(root);await expect(tools.senior_pm_config.execute({},context(root))).rejects.toThrow(/identity|pathname/);});
  it("preserves the root capability across every runtime tool after pathname replacement",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"spm-runtime-cap-")),pinned=await PinnedRepositoryRoot.open(root),identity=await stat(root),tools=createRuntimeTools({root,pinnedRoot:pinned,rootIdentity:{dev:identity.dev,ino:identity.ino},settings:structuredClone(DEFAULT_SETTINGS),client:{},nonce:new HandoffNonceStore(),hostConfig:{}});try{await rename(root,`${root}-original`);await mkdir(root);await writeFile(path.join(root,"replacement.txt"),"replacement secret");const calls=[()=>tools.senior_pm_discover.execute({},context(root)),()=>tools.senior_pm_write_spec.execute({input:specFixture()},context(root)),()=>tools.senior_pm_validate_spec.execute({artifactBase:"sample.r001"},context(root)),()=>tools.senior_pm_handoff.execute({artifactBase:"sample.r001"},context(root)),()=>tools.senior_pm_write_spec.execute({input:specFixture(),approvalSidecar:"review.json"},context(root))];for(const call of calls)await expect(call()).rejects.toThrow(/pathname|identity/);}finally{await pinned.close();}});
  it("requires fresh registry proof and matching server-side intent for explicit invocation",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"spm-explicit-")),identity=await stat(root),nonce=new HandoffNonceStore(),calls:any[]=[];let registered=false;const client={app:{agents:async()=>({data:registered?[{name:"engineer"}]:[{name:"other"}]})},session:{create:async(x:any)=>{calls.push(x);return{data:{id:"child"}}},prompt:async(x:any)=>{calls.push(x);return{data:{ok:true}}}}};const settings={...structuredClone(DEFAULT_SETTINGS),invocation_target:"engineer",allow_programmatic_invocation:true};const tools=createRuntimeTools({root,rootIdentity:{dev:identity.dev,ino:identity.ino},settings,client,nonce,hostConfig:{agent:{engineer:{}}}});const written=JSON.parse(await tools.senior_pm_write_spec.execute({input:specFixture()},context(root)) as string);nonce.issue("session",{artifactBase:written.artifactBase,target:"engineer"});const hinted=JSON.parse(await tools.senior_pm_handoff.execute({artifactBase:written.artifactBase,target:"engineer"},context(root)) as string);expect(hinted.refused).toMatch(/not currently registered/);expect(calls).toEqual([]);registered=true;nonce.issue("session",{artifactBase:written.artifactBase,target:"engineer"});const success=JSON.parse(await tools.senior_pm_handoff.execute({artifactBase:written.artifactBase,target:"engineer"},context(root)) as string);expect(success).toMatchObject({mode:"programmatic",target:"engineer",sessionID:"child",implementationMayBegin:false});expect(calls[1].body.agent).toBe("engineer");});
  it("exposes no production edit or shell tool", async () => { const { tools } = await runtime(); expect(Object.keys(tools)).toEqual(["senior_pm_config", "senior_pm_discover", "senior_pm_write_spec", "senior_pm_validate_spec", "senior_pm_handoff"]); });
});
