import { lstat, realpath, stat } from "node:fs/promises";
import path from "node:path";
import { tool } from "@opencode-ai/plugin";
import type { ToolDefinition } from "@opencode-ai/plugin";
import { evaluationPolicyFromConfig, type SeniorPmSettings } from "../config/index.js";
import { discoverRepository } from "../repository/index.js";
import { SCHEMA_VERSION, SPEC_FORMATS, SPEC_LIMITS, type ProductSpecInput } from "../spec/contract.js";
import { deterministicJson, sha256 } from "../spec/normalize.js";
import { inspectApprovalSidecar, writeRevision } from "../spec/writer.js";
import { validateArtifactSet } from "../validation/artifacts.js";
import { evaluateSpec, productContentHash } from "../validation/validate.js";
import { manualGuidance, discoverCandidates, invokeChild, registeredAgentIDs, type StandardClient } from "../workflow/handoff.js";
import type { HandoffNonceStore } from "../workflow/nonce.js";
import { PinnedRepositoryRoot, type RepositoryRoot } from "../shared/secure-fs.js";

const pz = tool.schema;
const text=pz.string().max(SPEC_LIMITS.string),nonempty=text.min(1),identifier=nonempty.max(SPEC_LIMITS.identifier).regex(SPEC_FORMATS.provenanceId),reference=nonempty.max(SPEC_LIMITS.path).regex(SPEC_FORMATS.safeReference);
const evidence = pz.object({ statement: nonempty, sources: pz.array(reference).max(SPEC_LIMITS.sources).optional() }).strict();
const strings = pz.array(text).max(SPEC_LIMITS.strings);
const sidecarPath=pz.string().max(SPEC_LIMITS.path).regex(/^(?!\/|[A-Za-z]:|\\)(?!.*(?:^|[\/\\])\.\.(?:[\/\\]|$))[A-Za-z0-9._\/\\-]+\.json$/);
export const productSpecInputSchema: any = pz.object({
  schemaVersion: pz.literal("1.0.0"), pluginVersion: identifier, specId: identifier, slug: pz.string().max(SPEC_LIMITS.slug).regex(SPEC_FORMATS.slug), revision: pz.number().int().positive(), generatedAt: pz.string().datetime(), title: text, hostIdentifier: identifier, requestedBy: identifier, pm: pz.object({ agent: identifier.optional(), model: identifier.optional() }).strict().optional(),
  executiveSummary: text, repositoryContext: text, targetUser: text, userProblem: text, desiredOutcome: text, proposedSolution: text, smallestShippableSlice: text, userStories: strings,
  functionalRequirements: pz.array(pz.object({ id: pz.string().regex(SPEC_FORMATS.functionalRequirementId), text: nonempty, repositoryClaim: pz.boolean().optional(), sources: pz.array(reference).max(SPEC_LIMITS.sources).optional() }).strict()).max(SPEC_LIMITS.requirements), acceptanceCriteria: pz.array(pz.object({ id: pz.string().regex(SPEC_FORMATS.acceptanceCriterionId), requirementIds: pz.array(pz.string().regex(SPEC_FORMATS.functionalRequirementId)).max(SPEC_LIMITS.criterionReferences), behavior: nonempty }).strict()).max(SPEC_LIMITS.criteria), uxExpectations: text, businessRules: strings, edgeCases: strings, nonFunctionalExpectations: strings, existingBehaviorToPreserve: strings, nonGoals: strings, futureConsiderations: strings, dependenciesAndConstraints: strings, definitionOfDone: pz.array(pz.object({ text: nonempty, acceptanceCriteria: pz.array(pz.string().regex(SPEC_FORMATS.acceptanceCriterionId)).max(SPEC_LIMITS.criterionReferences) }).strict()).max(SPEC_LIMITS.definitionOfDone), handoffInstructions: text,
  evidence: pz.object({ facts: pz.array(evidence).max(SPEC_LIMITS.evidencePerGroup), inferences: pz.array(evidence).max(SPEC_LIMITS.evidencePerGroup), assumptions: pz.array(evidence).max(SPEC_LIMITS.evidencePerGroup), unresolved: pz.array(evidence).max(SPEC_LIMITS.evidencePerGroup) }).strict(), interfaceImpact: pz.enum(["none", "content_only", "minor_interaction", "substantial_ui", "major_visual_direction", "unknown"]), contentChangesHierarchy: pz.boolean().optional(), contentChangesPublicBrand: pz.boolean().optional(), relevantStates: pz.array(pz.enum(["success", "error", "empty", "loading", "permission", "interruption", "recovery", "duplicate", "partial"])).max(SPEC_LIMITS.relevantStates).optional(), highRiskBlockers: strings.optional(), technicalPlanningRequired: pz.boolean().optional(), additionalSections: pz.array(pz.object({ id: pz.string().max(SPEC_LIMITS.identifier).regex(SPEC_FORMATS.sectionId), title: nonempty, body: text }).strict()).max(SPEC_LIMITS.additionalSections).optional()
}).strict();
function outputRoot(settings: SeniorPmSettings) { return settings.specification_directory === "auto" || !settings.specification_directory ? ".opencode/specs/senior-pm" : settings.specification_directory; }
function evaluationPolicy(settings: SeniorPmSettings) { const value=evaluationPolicyFromConfig(settings); return { ...(value.additionalNonGoals.length?{additionalNonGoals:value.additionalNonGoals}:{}), ...(value.requiredAdditionalSections.length?{requiredAdditionalSections:value.requiredAdditionalSections}:{}) }; }
function result(value: unknown) { return JSON.stringify(value, null, 2); }
export interface ToolRuntime { root: string; pinnedRoot?: PinnedRepositoryRoot; rootIdentity?: { dev: number; ino: number }; settings: SeniorPmSettings; client: StandardClient; nonce: HandoffNonceStore; hostConfig: any; diagnostics?: string[] }
export interface RuntimeTools { [key: string]: ToolDefinition; senior_pm_config: ToolDefinition; senior_pm_discover: ToolDefinition; senior_pm_write_spec: ToolDefinition; senior_pm_validate_spec: ToolDefinition; senior_pm_handoff: ToolDefinition }
export async function approvalSidecarDigest(repositoryRoot: RepositoryRoot, configuredOutputRoot: string, relativeInput: string) { const inspected=await inspectApprovalSidecar(repositoryRoot,configuredOutputRoot,relativeInput); return {path:inspected.path,digest:inspected.sha256,identity:inspected.identity}; }
export function createRuntimeTools(runtime: ToolRuntime): RuntimeTools {
  const operationRoot:RepositoryRoot = runtime.pinnedRoot ?? runtime.root;
  const operationPath = runtime.pinnedRoot?.descriptorPath ?? runtime.root;
  const assertRoot = async () => { await runtime.pinnedRoot?.assertIdentity(); const resolved = await realpath(runtime.root), current = await stat(resolved); if (resolved !== runtime.root || (runtime.rootIdentity && (current.dev !== runtime.rootIdentity.dev || current.ino !== runtime.rootIdentity.ino))) throw new Error("Pinned host root pathname changed"); };
  const validateContext = async (context:any) => { await assertRoot();const supplied=context?.directory;if(typeof supplied!=="string"||!supplied)throw new Error("Tool context directory is required");const suppliedStat=await lstat(supplied);if(!suppliedStat.isDirectory()||suppliedStat.isSymbolicLink())throw new Error("Tool context directory is unsafe");const directory=await realpath(supplied);if(directory!==runtime.root&&!directory.startsWith(`${runtime.root}${path.sep}`))throw new Error("Tool context directory is outside pinned host root");const hint=context?.worktree;if(typeof hint!=="string"||!hint)return;try{const hintStat=await lstat(hint);if(!hintStat.isDirectory()||hintStat.isSymbolicLink())return;const worktree=await realpath(hint);if(worktree===path.parse(worktree).root)return;const git=path.join(worktree,".git"),gitStat=await lstat(git);if(!gitStat.isDirectory()||gitStat.isSymbolicLink()||await realpath(git)!==git)return;if(worktree!==runtime.root)throw new Error("Verified ToolContext worktree does not match pinned host root");}catch(error){if(error instanceof Error&&error.message==="Verified ToolContext worktree does not match pinned host root")throw error;}};
  const configTool = tool({ description: "Return sanitized Senior PM configuration and capabilities.", args: {}, async execute(_args, context) { await validateContext(context); const s = runtime.settings; return result({ pluginVersion: "0.1.0", schemaVersion: SCHEMA_VERSION, enabled: s.enabled, mode: s.mode, model: s.model, effort: s.effort, specificationDirectory: s.specification_directory, outputRoot: outputRoot(s), capabilities: { repositoryDiscovery: true, immutableSpecificationWriting: true, externalResearch: !!s.allow_external_research, repositoryHistory: !!s.allow_repository_history, programmaticHandoff: !!s.allow_programmatic_invocation }, limitations: ["No production-code writes", "Auto handoff never invokes", "No factual-correctness guarantee"], trustDiagnostics: runtime.diagnostics ?? ["Project and tuple sources cannot widen operator capabilities"] }); } });
  const discoverTool = tool({ description: "Discover bounded normalized repository context and requested safe detail paths as untrusted evidence.", args: { detail_paths: pz.array(reference).max(20).optional() }, async execute(args, context) { await validateContext(context); const l = runtime.settings.context_limits ?? {}; const limits = Object.fromEntries(Object.entries({ maxDepth: l.max_depth, maxFiles: l.max_files, maxFileBytes: l.max_file_bytes, maxTotalBytes: l.max_total_bytes, timeoutMs: l.timeout_ms }).filter(([,v]) => v !== undefined)); return result(await discoverRepository(operationRoot, { limits, detailPaths: args.detail_paths ?? [], allowHistory: !!runtime.settings.allow_repository_history, historyAuthorized: !!runtime.settings.allow_repository_history })); } });
  const writeTool = tool({ description: "Validate structured product input and write one immutable specification revision.", args: { input: productSpecInputSchema, approvalSidecar: sidecarPath.optional(), priorArtifact: pz.object({ base: pz.string().max(SPEC_LIMITS.path).regex(SPEC_FORMATS.artifactBase) }).strict().optional() }, async execute(args, context) { await validateContext(context); const root = outputRoot(runtime.settings); const priorArtifact = args.priorArtifact ? { repositoryRoot: operationRoot, outputRoot: root, base: args.priorArtifact.base } : undefined; let approval: { path: string; digest: string;identity:{specId:string;revision:number;productContentHash:string} } | undefined; if (args.approvalSidecar) { approval = await approvalSidecarDigest(operationRoot, root, args.approvalSidecar);const expectedHash=productContentHash(args.input as ProductSpecInput);if(approval.identity.specId!==args.input.specId||approval.identity.revision!==args.input.revision||approval.identity.productContentHash!==expectedHash)throw new Error("Approval sidecar identity does not match the pending specification"); if (typeof context.ask !== "function") throw new Error("Approval sidecar ingestion requires user authorization"); await context.ask({ permission: "senior_pm_approval_sidecar", patterns: [`${approval.path}#sha256=${approval.digest};spec=${approval.identity.specId};revision=${approval.identity.revision};product=${approval.identity.productContentHash}`], always: [], metadata: { path: approval.path, sha256: approval.digest, specId: approval.identity.specId, revision: approval.identity.revision,productContentHash:approval.identity.productContentHash } }); const after = await approvalSidecarDigest(operationRoot, root, args.approvalSidecar); if (after.digest !== approval.digest || after.path !== approval.path) throw new Error("Approval sidecar changed after user authorization"); }
    const written = await writeRevision(operationRoot, args.input as ProductSpecInput, { outputRoot: root, policy: evaluationPolicy(runtime.settings), ...(approval ? { approvalSidecar: approval.path, expectedApprovalSha256: approval.digest } : {}), ...(priorArtifact ? { priorArtifact } : {}) }); const spec = written.spec; return result({ artifactBase: written.base, outputRoot: written.outputRoot, paths: written.paths, failures: spec.validationFailures, status: spec.status, reason: spec.statusReason, implementationMayBegin: spec.status === "Ready for implementation", priorArtifactBase: args.priorArtifact?.base }); } });
  const validateTool = tool({ description: "Validate an in-memory structured draft or committed artifact set without writing or accepting approval data.", args: { input: productSpecInputSchema.optional(), artifactBase: pz.string().max(SPEC_LIMITS.path).regex(SPEC_FORMATS.artifactBase).optional() }, async execute(args, context) { await validateContext(context); if (args.input) return result(evaluateSpec(args.input as ProductSpecInput, evaluationPolicy(runtime.settings))); if (!args.artifactBase) throw new Error("input or artifactBase is required"); return result(await validateArtifactSet(operationRoot, outputRoot(runtime.settings), args.artifactBase,{currentPolicy:evaluationPolicy(runtime.settings)})); } });
  const handoffTool = tool({ description: "Validate a committed artifact, then prepare manual handoff or invoke an explicitly authorized exact target.", args: { artifactBase: pz.string().max(SPEC_LIMITS.path).regex(SPEC_FORMATS.artifactBase), target: identifier.optional() }, async execute(args, context) { await validateContext(context); const checked = await validateArtifactSet(operationRoot, outputRoot(runtime.settings), args.artifactBase,{currentPolicy:evaluationPolicy(runtime.settings)}); if (!checked.valid || !checked.spec?.handoffEligible) return result({ mode: "refused", artifactBase: args.artifactBase, failures: checked.failures, status: checked.spec?.status, reason: checked.spec?.statusReason ?? "Committed artifact is invalid, absent, or not handoff eligible", implementationMayBegin: false }); const spec = checked.spec, canonicalHash=sha256(deterministicJson(spec)), target = runtime.settings.invocation_target, candidates = discoverCandidates(runtime.hostConfig, runtime.settings.handoff_candidates), manual = { ...manualGuidance(args.artifactBase, candidates), status: spec.status, reason: spec.statusReason, productHash: spec.productContentHash, canonicalHash, implementationMayBegin: spec.status === "Ready for implementation" }; if (!target || target === "auto") return result(manual); if (args.target !== target || !runtime.settings.allow_programmatic_invocation || !runtime.nonce.consume(context.sessionID, { artifactBase: args.artifactBase, target })) return result({ ...manual, refused: "Programmatic handoff lacks matching user-authorized /pm-handoff intent" }); let registered: string[]; try { registered = await registeredAgentIDs(runtime.client); } catch (error) { return result({ ...manual, refused: (error as Error).message }); } if (!registered.includes(target)) return result({ ...manual, refused: "Configured invocation target is not currently registered" }); try { const sessionID = await invokeChild(runtime.client, context.sessionID, target, path.join(operationPath, outputRoot(runtime.settings), args.artifactBase)); return result({ mode: "programmatic", target, sessionID, status: spec.status, reason: spec.statusReason, productHash: spec.productContentHash, canonicalHash, implementationMayBegin: spec.status === "Ready for implementation" }); } catch (error) { return result({ ...manual, refused: `Child-session handoff failed: ${(error as Error).message}` }); } } });
  return { senior_pm_config: configTool, senior_pm_discover: discoverTool, senior_pm_write_spec: writeTool, senior_pm_validate_spec: validateTool, senior_pm_handoff: handoffTool };
}
