import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cp, lstat, mkdtemp, readdir, readFile, realpath } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { ProductSpecInput } from "../../../src/spec/contract.js";
export const fixturesRoot=path.resolve(import.meta.dirname,"../../fixtures/core");
export async function copyFixture(name:string){const source=path.join(fixturesRoot,name),root=execFileSync("git",["rev-parse","--show-toplevel"],{cwd:source,encoding:"utf8"}).trim(),relative=path.relative(root,source),files=execFileSync("git",["ls-files","-z","--",relative],{cwd:root,encoding:"utf8"}).split("\0").filter(Boolean).map(file=>path.join(root,file)),allowed=new Set(files),directories=new Set([source]);for(const file of files)for(let directory=path.dirname(file);directory.startsWith(source);directory=path.dirname(directory)){directories.add(directory);if(directory===source)break;}const target=await mkdtemp(path.join(os.tmpdir(),`spm-core-${name}-`));await cp(source,target,{recursive:true,filter:entry=>allowed.has(entry)||directories.has(entry)});return target;}
export async function treeHash(root:string,excludeOwned=false){const hash=createHash("sha256");async function walk(dir:string){for(const name of (await readdir(dir)).sort()){const file=path.join(dir,name),rel=path.relative(root,file).replaceAll(path.sep,"/");if(excludeOwned&&(rel===".opencode/specs/senior-pm"||rel.startsWith(".opencode/specs/senior-pm/")))continue;const stat=await lstat(file);if(stat.isSymbolicLink()){hash.update(`L${rel}:${await realpath(file).catch(()=>"broken")}`);}else if(stat.isDirectory()){await walk(file);}else{hash.update(`F${rel}:${stat.mode}:${stat.size}:`);hash.update(await readFile(file));}}}await walk(root);return hash.digest("hex");}
export function canonicalInput(hostIdentifier="fixture-host"):ProductSpecInput{return{schemaVersion:"1.0.0",pluginVersion:"0.1.0",specId:"SPEC-CORE-1",slug:"portable-checkpoint",revision:1,generatedAt:"2026-07-18T12:00:00.000Z",title:"Portable checkpoint recovery",hostIdentifier,requestedBy:"integration-user",pm:{agent:"senior-pm",model:"fixture-model"},executiveSummary:"Restore interrupted work from one checkpoint.",repositoryContext:"The fixture contains a bounded workflow.",targetUser:"Fixture operators",userProblem:"Interrupted work cannot resume safely.",desiredOutcome:"A user resumes once without duplicate effects.",proposedSolution:"Persist and restore a checkpoint.",smallestShippableSlice:"Resume one interrupted operation.",userStories:["As an operator, I resume interrupted work."],functionalRequirements:[{id:"FR-001",text:"Record and restore one checkpoint",sources:["README.md:1"]}],acceptanceCriteria:[{id:"AC-001",requirementIds:["FR-001"],behavior:"Given an interruption, when resume is selected, then the checkpoint is restored once"}],uxExpectations:"Display the restored checkpoint and completion state.",businessRules:["Only one active resume is permitted."],edgeCases:["A duplicate resume is rejected."],nonFunctionalExpectations:["Checkpoint content remains private."],existingBehaviorToPreserve:["Completed operations remain unchanged."],nonGoals:["No billing behavior is added.","No production source files are modified."],futureConsiderations:["Multiple checkpoints may be considered later after evidence."],dependenciesAndConstraints:["Use the existing fixture storage boundary."],definitionOfDone:[{text:"The resume criterion passes.",acceptanceCriteria:["AC-001"]}],handoffInstructions:"Plan implementation against FR-001 and AC-001.",evidence:{facts:[{statement:"The fixture README describes its purpose.",sources:["README.md:1"]}],inferences:[],assumptions:[{statement:"Fixture storage can represent one checkpoint."}],unresolved:[]},interfaceImpact:"none",relevantStates:["success","error","interruption","recovery","duplicate"],technicalPlanningRequired:true,additionalSections:[{id:"integration-notes",title:"Integration notes",body:"This section is declared by the fixture test."}]};}
