import { z } from "zod";
import { isMeaningfulContent, SPEC_FORMATS as F, SPEC_LIMITS as L } from "../spec/limits.js";
const text=z.string().max(L.string),nonempty=text.min(1),strings=z.array(text).max(L.strings),identifier=nonempty.max(L.identifier).regex(F.provenanceId),reference=nonempty.max(L.path).regex(F.safeReference),hash=z.string().regex(F.sha256);
const evidence=z.object({statement:nonempty,sources:z.array(reference).max(L.sources).optional()}).strict();
const status=z.enum(["Draft","Blocked by product decision","Ready for design review","Ready for technical planning","Ready for implementation","Returned for product revision"]);
export const failureSchema=z.object({code:text,path:text,message:text}).strict();
export const productSpecInputSchema=z.object({
 schemaVersion:z.literal("1.0.0"),pluginVersion:identifier,specId:identifier,slug:z.string().max(L.slug).regex(F.slug),revision:z.number().int().positive(),generatedAt:z.string().datetime(),title:text,hostIdentifier:identifier,requestedBy:identifier,pm:z.object({agent:identifier.optional(),model:identifier.optional()}).strict().optional(),
 executiveSummary:text,repositoryContext:text,targetUser:text,userProblem:text,desiredOutcome:text,proposedSolution:text,smallestShippableSlice:text,userStories:strings,
 functionalRequirements:z.array(z.object({id:z.string().regex(F.functionalRequirementId),text:nonempty,repositoryClaim:z.boolean().optional(),sources:z.array(reference).max(L.sources).optional()}).strict()).max(L.requirements),acceptanceCriteria:z.array(z.object({id:z.string().regex(F.acceptanceCriterionId),requirementIds:z.array(z.string().regex(F.functionalRequirementId)).max(L.criterionReferences),behavior:nonempty}).strict()).max(L.criteria),
 uxExpectations:text,businessRules:strings,edgeCases:strings,nonFunctionalExpectations:strings,existingBehaviorToPreserve:strings,nonGoals:strings,futureConsiderations:strings,dependenciesAndConstraints:strings,definitionOfDone:z.array(z.object({text:nonempty,acceptanceCriteria:z.array(z.string().regex(F.acceptanceCriterionId)).max(L.criterionReferences)}).strict()).max(L.definitionOfDone),handoffInstructions:text,
 evidence:z.object({facts:z.array(evidence).max(L.evidencePerGroup),inferences:z.array(evidence).max(L.evidencePerGroup),assumptions:z.array(evidence).max(L.evidencePerGroup),unresolved:z.array(evidence).max(L.evidencePerGroup)}).strict(),interfaceImpact:z.enum(["none","content_only","minor_interaction","substantial_ui","major_visual_direction","unknown"]),contentChangesHierarchy:z.boolean().optional(),contentChangesPublicBrand:z.boolean().optional(),relevantStates:z.array(z.enum(["success","error","empty","loading","permission","interruption","recovery","duplicate","partial"])).max(L.relevantStates).optional(),highRiskBlockers:strings.optional(),technicalPlanningRequired:z.boolean().optional(),additionalSections:z.array(z.object({id:z.string().max(L.identifier),title:nonempty,body:text}).strict()).max(L.additionalSections).optional()
}).strict();
export const evaluatedSpecSchema=productSpecInputSchema.extend({status,statusReason:nonempty,validationFailures:z.array(failureSchema).max(L.failures),designReviewRequired:z.boolean(),designApproved:z.boolean(),handoffEligible:z.boolean(),productContentHash:hash,evaluationPolicy:z.object({additionalNonGoals:z.array(nonempty).max(L.policyNonGoals).optional(),requiredAdditionalSections:z.array(nonempty).max(L.policySections).optional()}).strict()}).strict();
const meaningfulIdentifier=identifier.refine(isMeaningfulContent,"must not be placeholder content"),meaningfulText=nonempty.refine(isMeaningfulContent,"must not be placeholder content");
export const designApprovalSchema=z.object({schemaVersion:z.literal("1.0.0"),specId:meaningfulIdentifier,revision:z.number().int().positive(),productContentHash:hash,decision:z.enum(["approved","changes_requested"]),reviewer:z.object({id:meaningfulIdentifier,name:meaningfulIdentifier,role:meaningfulIdentifier.optional()}).strict(),reviewedAt:z.string().datetime(),evidence:meaningfulText}).strict();
export const handoffSchema=z.object({schemaVersion:z.literal("1.0.0"),specId:identifier,revision:z.number().int().positive(),status,canonicalContentHash:hash,productContentHash:hash,generatedAt:z.string().datetime(),hostIdentifier:identifier,requestedBy:identifier,instructions:text,validationFailures:z.array(failureSchema).max(L.failures),handoffEligible:z.boolean()}).strict();
const persisted=z.object({file:z.string().max(L.path).regex(F.persistedFile),sha256:hash}).strict();
export const manifestSchema=z.object({schemaVersion:z.literal("1.0.0"),specId:identifier,revision:z.number().int().positive(),status,canonicalContentHash:hash,committed:z.literal(true),files:z.object({canonicalJson:hash,markdown:hash,handoffJson:hash,designReview:persisted.optional(),priorArtifact:persisted.optional()}).strict()}).strict();
export const artifactIdentitySchema=z.object({specId:identifier,revision:z.number().int().positive(),status,schemaVersion:z.literal("1.0.0"),canonicalContentHash:hash}).strict();
export const priorArtifactMetadataSchema=z.object({schemaVersion:z.literal("1.0.0"),specId:identifier,slug:z.string().max(L.slug).regex(F.slug),hostIdentifier:identifier,revision:z.number().int().positive(),base:z.string().max(L.path).regex(F.artifactBase)}).strict();
