import type { DesignReviewApproval, EvaluationPolicy, Failure, ProductSpecInput } from "../spec/contract.js";
import { deterministicJson, sha256 } from "../spec/normalize.js";
import { isMeaningfulContent, SPEC_FORMATS } from "../spec/limits.js";
import { HANDOFF_ELIGIBLE, decideReadiness, requiresDesignReview } from "./readiness.js";
import { designApprovalSchema, productSpecInputSchema } from "./schemas.js";
const VAGUE = /\b(user[- ]friendly|intuitive|seamless|easy|fast|modern|beautiful|robust|appropriate|as needed|etc\.?|works well)\b/i;
const OBSERVABLE = /\b(given\b[\s\S]*\bwhen\b[\s\S]*\bthen\b)|\b(displays?|returns?|rejects?|creates?|prevents?|records?|remains?|redirects?|allows?)\b/i;
export function productContentHash(input: ProductSpecInput): string { return sha256(deterministicJson(input)); }
export function parseDesignApproval(raw: unknown, spec: ProductSpecInput): DesignReviewApproval | undefined {
  if (typeof raw === "string") { try { raw = JSON.parse(raw); } catch { return undefined; } }
  const parsed = designApprovalSchema.safeParse(raw); if (!parsed.success) return undefined;
  const a = parsed.data; const pm = [spec.pm?.agent, spec.requestedBy].filter(Boolean);
  if (a.specId !== spec.specId || a.revision !== spec.revision || a.productContentHash !== productContentHash(spec) || a.decision !== "approved" || pm.includes(a.reviewer.id) || ![a.specId,a.reviewer.id,a.reviewer.name,a.evidence,...(a.reviewer.role?[a.reviewer.role]:[])].every(isMeaningfulContent)) return undefined;
  return a;
}
export function validateProduct(input: ProductSpecInput, policy: EvaluationPolicy = {}): Failure[] {
  const f: Failure[] = []; const add = (code: string, path: string, message: string) => f.push({ code, path, message });
  const meaningful = isMeaningfulContent;
  for (const [path, value] of [["title", input.title], ["executiveSummary",input.executiveSummary],["repositoryContext",input.repositoryContext],["targetUser",input.targetUser],["userProblem", input.userProblem], ["desiredOutcome", input.desiredOutcome],["proposedSolution",input.proposedSolution], ["smallestShippableSlice", input.smallestShippableSlice],["uxExpectations",input.uxExpectations], ["handoffInstructions", input.handoffInstructions]] as const) if (!meaningful(value)) add("content.required", path, `${path} must be meaningful and non-empty`);
  if (!input.userStories.some(meaningful)) add("content.stories","userStories","At least one meaningful user story is required");
  if (!input.definitionOfDone.some(item=>meaningful(item.text))) add("content.done","definitionOfDone","Definition of done is required");
  if (!input.existingBehaviorToPreserve.some(meaningful)) add("content.preserve", "existingBehaviorToPreserve", "Preserved behavior is required (use an explicit meaningful no-prior-behavior statement when applicable)");
  if (!input.nonGoals.some(meaningful)) add("scope.non_goals", "nonGoals", "At least one meaningful non-goal is required");
  for (const [path, values] of [["businessRules",input.businessRules],["edgeCases",input.edgeCases],["nonFunctionalExpectations",input.nonFunctionalExpectations],["dependenciesAndConstraints",input.dependenciesAndConstraints]] as const) if (!values.some(meaningful)) add("content.required",path,`${path} requires meaningful content or Not applicable — <reason>`);
  for(const [path,values] of [["userStories",input.userStories],["businessRules",input.businessRules],["edgeCases",input.edgeCases],["nonFunctionalExpectations",input.nonFunctionalExpectations],["existingBehaviorToPreserve",input.existingBehaviorToPreserve],["nonGoals",input.nonGoals],["dependenciesAndConstraints",input.dependenciesAndConstraints]] as const)values.forEach((value,i)=>{if(!meaningful(value))add("content.placeholder",`${path}.${i}`,`${path} contains placeholder content`);});
  input.futureConsiderations.forEach((value,i)=>{if(!meaningful(value))add("content.placeholder",`futureConsiderations.${i}`,"Future consideration contains placeholder content");});
  for(const [path,value] of [["specId",input.specId],["pluginVersion",input.pluginVersion],["hostIdentifier",input.hostIdentifier],["requestedBy",input.requestedBy],["pm.agent",input.pm?.agent],["pm.model",input.pm?.model]] as const)if(value!==undefined&&(!meaningful(value)||!SPEC_FORMATS.provenanceId.test(value)))add("provenance.invalid",path,`${path} must be meaningful safe provenance metadata`);
  if (!input.functionalRequirements.length) add("fr.required", "functionalRequirements", "At least one FR is required");
  const ids = new Set<string>(); input.functionalRequirements.forEach((r, i) => { if (!/^FR-\d{3}$/.test(r.id) || ids.has(r.id)) add("fr.id", `functionalRequirements.${i}.id`, "FR ID must be unique FR-###"); ids.add(r.id); if (!meaningful(r.text)) add("fr.text", `functionalRequirements.${i}.text`, "FR text must be meaningful"); if (r.repositoryClaim && !r.sources?.length) add("evidence.repository", `functionalRequirements.${i}.sources`, "Repository claims require evidence");r.sources?.forEach((source,j)=>{if(!meaningful(source)||!SPEC_FORMATS.safeReference.test(source))add("fr.source",`functionalRequirements.${i}.sources.${j}`,"FR source must be a meaningful safe reference");}); });
  if (!input.acceptanceCriteria.length) add("ac.required", "acceptanceCriteria", "At least one AC is required");
  const acs = new Set<string>(); input.acceptanceCriteria.forEach((a, i) => { if (!/^AC-\d{3}$/.test(a.id) || acs.has(a.id)) add("ac.id", `acceptanceCriteria.${i}.id`, "AC ID must be unique AC-###"); acs.add(a.id); if (!a.requirementIds.length || a.requirementIds.some(x => !ids.has(x))) add("ac.reference", `acceptanceCriteria.${i}.requirementIds`, "AC must reference existing FR IDs"); if (!meaningful(a.behavior)||!OBSERVABLE.test(a.behavior)) add("ac.observable", `acceptanceCriteria.${i}.behavior`, "AC must be observable and non-placeholder"); if (VAGUE.test(a.behavior)) add("language.vague", `acceptanceCriteria.${i}.behavior`, "Criterion contains vague wording"); });
  for (const id of ids) if (!input.acceptanceCriteria.some(ac => ac.requirementIds.includes(id as `FR-${string}`) && OBSERVABLE.test(ac.behavior))) add("ac.coverage", `functionalRequirements.${id}`, "Every FR must have at least one observable AC");
  const covered=new Set<string>();input.definitionOfDone.forEach((item,i)=>{if(!meaningful(item.text))add("dod.placeholder",`definitionOfDone.${i}.text`,"DoD text must be meaningful");for(const id of item.acceptanceCriteria){if(!acs.has(id))add("dod.unknown",`definitionOfDone.${i}.acceptanceCriteria`,`Unknown AC ID: ${id}`);if(covered.has(id))add("dod.duplicate",`definitionOfDone.${i}.acceptanceCriteria`,`Duplicate DoD coverage: ${id}`);covered.add(id);}});for(const id of acs)if(!covered.has(id))add("dod.coverage","definitionOfDone",`Accepted criterion is not covered by DoD: ${id}`);
  for(const group of ["facts","inferences","assumptions","unresolved"] as const)input.evidence[group].forEach((item,i)=>{if(!meaningful(item.statement))add("evidence.placeholder",`evidence.${group}.${i}.statement`,"Evidence statement must be meaningful");item.sources?.forEach((source,j)=>{if(!meaningful(source)||!SPEC_FORMATS.safeReference.test(source))add("evidence.source",`evidence.${group}.${i}.sources.${j}`,"Evidence source must be a meaningful safe reference");});if(group==="facts"&&!item.sources?.length)add("evidence.fact",`evidence.facts.${i}.sources`,"Confirmed facts require source evidence");});
  if (VAGUE.test(input.uxExpectations) || VAGUE.test(input.handoffInstructions)) add("language.vague", "uxExpectations", "UX/handoff wording contains vague language");
  for (const goal of policy.additionalNonGoals ?? []) if (!input.nonGoals.includes(goal)) add("policy.non_goal", "nonGoals", `Configured non-goal is missing: ${goal}`);
  const extras = new Map((input.additionalSections ?? []).map(section => [section.id, section])); for(const [i,section] of (input.additionalSections??[]).entries())if(!meaningful(section.id)||!SPEC_FORMATS.sectionId.test(section.id)||!meaningful(section.title)||!meaningful(section.body))add("additional.placeholder",`additionalSections.${i}`,"Additional section ID/title/body must be meaningful and safe");for (const id of policy.requiredAdditionalSections ?? []) if (!extras.has(id) || !meaningful(extras.get(id)!.body)) add("policy.section", `additionalSections.${id}`, `Configured required section is missing meaningful content: ${id}`);
  return f;
}
type InternalEvaluationContext = { validatedPriorStatus?: import("../spec/contract.js").SpecStatus | undefined };
export function evaluateSpec(input: ProductSpecInput, policy: EvaluationPolicy = {}) { return evaluateSpecInternal(input, undefined, {}, policy); }
export function evaluateSpecInternal(input: ProductSpecInput, rawApproval: unknown, context: InternalEvaluationContext, policy: EvaluationPolicy = {}) {
  const parsed = productSpecInputSchema.safeParse(input); if (!parsed.success) throw new Error(`Invalid ProductSpecInput: ${parsed.error.issues.map(x=>`${x.path.join(".")}: ${x.message}`).join("; ")}`); input = parsed.data as unknown as ProductSpecInput;
  const failures = validateProduct(input, policy), designReviewRequired = requiresDesignReview(input), parsedApproval = parseDesignApproval(rawApproval, input); if(rawApproval!==undefined&&!parsedApproval)throw new Error("External design approval is malformed, mismatched, stale, or self-approved");const designApproved = !!parsedApproval, highRiskBlocked = !!input.highRiskBlockers?.length;
  const status = decideReadiness({ failures, highRiskBlocked, designReviewRequired, designApproved, technicalPlanningRequired: input.technicalPlanningRequired !== false, priorStatus: context.validatedPriorStatus });
  const statusReason = status === "Returned for product revision" ? "A validated prior ready revision now fails validation." : status === "Blocked by product decision" ? "A high-risk product decision remains unresolved." : status === "Draft" ? `${failures.length} deterministic validation failure(s) remain.` : status === "Ready for design review" ? "External design approval is required." : status === "Ready for technical planning" ? "Validation passed and technical planning is required." : "Validation passed and no technical planning gate is required.";
  return { ...input, status, statusReason, validationFailures: failures, designReviewRequired, designApproved, handoffEligible: !failures.length && !highRiskBlocked && HANDOFF_ELIGIBLE[status], productContentHash: productContentHash(input), evaluationPolicy: policy };
}
export const validateSpec = evaluateSpec;
