import { execFile } from "node:child_process"; import { constants } from "node:fs"; import * as nativeFs from "node:fs/promises"; import path from "node:path"; import { promisify } from "node:util";
import type { DiscoverOptions, Evidence, RepositoryContext, RepositoryLimits } from "./types.js";
import { assertDescriptorTarget, openPinnedDirectory, PinnedRepositoryRoot, procDescriptorTarget, repositoryCanonicalPath, repositoryDescriptorPath, type RepositoryRoot } from "../shared/secure-fs.js";
const exec = promisify(execFile), DEFAULT: RepositoryLimits = { maxDepth: 6, maxFiles: 200, maxFileBytes: 64000, maxTotalBytes: 1000000, timeoutMs: 3000 };
const EXCLUDED = new Set([".git", ".hg", ".svn", "node_modules", "vendor", "dist", "build", "coverage", "target", ".cache", ".next", "out", "tmp"]), SENSITIVE = /(^|\/)(\.env(?:\..*)?|\.aws\/credentials|config\/secrets?[^/]*|[^/]*(?:credentials?|secrets?|tokens?|private[-_]?keys?|id_rsa|auth(?:store)?)[^/]*|[^/]*\.(?:pem|p12|key))($|\/)/i, BINARY = /\.(png|jpe?g|gif|webp|ico|pdf|zip|gz|tar|7z|woff2?|ttf|mp[34]|mov|sqlite|lock)$/i;
const DOC = /^(readme|changelog|contributing)|\.(md|mdx|rst|adoc)$/i, TEST = /(^|[._-])(test|spec)([._-]|$)|(^|\/)tests?\//i, AGENT = /(^|\/)(agents?\.md|claude\.md|\.opencode\/)/i, UI = /(^|\/)(styles?|components?|views?|templates?|public)\//i, MANIFEST = /(^|\/)(package\.json|pyproject\.toml|cargo\.toml|go\.mod|gemfile|composer\.json|pom\.xml|build\.gradle|makefile)$/i;
export function redactSecrets(text: string) { return text
  .replace(/-----BEGIN [^-]+ PRIVATE KEY-----[\s\S]*?-----END [^-]+ PRIVATE KEY-----/g, "[REDACTED PRIVATE KEY]")
  .replace(/\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^\s"']+/gi, "[REDACTED DATABASE URL]")
  .replace(/\bAKIA[0-9A-Z]{16}\b/g, "[REDACTED AWS KEY]").replace(/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g, "[REDACTED JWT]")
  .replace(/\b(?:Bearer|Basic)\s+[A-Za-z0-9+/_=.-]+/gi, "[REDACTED AUTHORIZATION]")
  .replace(/(aws_secret_access_key|api[_-]?key|access[_-]?key|client[_-]?secret|token|secret|password|authorization|credentials?)\s*[:=]\s*["']?[^\s"']+/gi, "$1=[REDACTED]")
  .replace(/\b(?:sk|ghp|github_pat|xox[baprs])[-_][A-Za-z0-9_-]{12,}\b/g, "[REDACTED]"); }
const category = (r: string) => AGENT.test(r) ? "agent_configuration" : TEST.test(r) ? "tests" : UI.test(r) ? "ui" : DOC.test(path.basename(r)) ? "documentation" : MANIFEST.test(r) ? "manifest" : "content";
async function verifyPinnedGitPath(handle:nativeFs.FileHandle,git:string,fs:Pick<typeof nativeFs,"lstat">){const pinned=await handle.stat(),current=await fs.lstat(git);if(current.isSymbolicLink()||current.dev!==pinned.dev||current.ino!==pinned.ino)throw new Error("git directory changed after pinning");}
const summary = (xs: string[]) => xs.map(x => x.trim()).filter(x => x.length > 2 && x.length < 240 && !/^([{}\[\],]|\/\/|#?\s*$)/.test(x)).slice(0, 6);
export async function discoverRepository(rootInput: RepositoryRoot, options: DiscoverOptions = {}): Promise<RepositoryContext> {
  const fs = { ...nativeFs, ...options.fs }, now = options.now ?? Date.now, platform = options.platform ?? process.platform, descriptorTarget = options.descriptorTarget ?? procDescriptorTarget, limits = { ...DEFAULT, ...options.limits }, deadline = now() + limits.timeoutMs, notices: string[] = []; const details = new Set((options.detailPaths ?? []).slice(0, 20).map(x => x.replaceAll("\\", "/")));
  const timed = async <T>(label: string, operation: Promise<T>): Promise<T> => { const left = deadline - now(); if (left <= 0) throw Object.assign(new Error("deadline"), { code: "SPM_TIMEOUT" }); let timer: NodeJS.Timeout; try { return await Promise.race([operation, new Promise<T>((_, reject) => { timer = setTimeout(() => reject(Object.assign(new Error(label), { code: "SPM_TIMEOUT" })), left); })]); } finally { clearTimeout(timer!); } };
  const root = await timed("root", repositoryCanonicalPath(rootInput)), ioRoot=repositoryDescriptorPath(rootInput); const rootStat = rootInput instanceof PinnedRepositoryRoot ? await rootInput.duplicate().then(async handle=>{try{return await handle.stat();}finally{await handle.close();}}) : await timed("root stat", fs.lstat(root)); if (!rootStat.isDirectory() || (!(rootInput instanceof PinnedRepositoryRoot) && rootStat.isSymbolicLink())) throw new Error("Pinned repository root is invalid");
  const inside = (p: string) => p === root || p.startsWith(`${root}${path.sep}`); let files = 0, bytes = 0, limited = false; const evidence: Evidence[] = [];
  async function walk(dir: string, depth: number, relativeDirectory=""): Promise<void> {
    if (depth > limits.maxDepth || files >= limits.maxFiles || bytes >= limits.maxTotalBytes || now() >= deadline) { limited = true; return; }
    let entries; try { const resolved = await timed("directory containment", fs.realpath(dir)); if (!inside(resolved)) throw new Error("outside"); entries = await timed("readdir", fs.readdir(dir, { withFileTypes: true })); } catch (e: any) { if (e.code === "SPM_TIMEOUT") limited = true; else notices.push("A repository entry became unreadable or changed during discovery."); return; }
    for (const entry of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
      if (files >= limits.maxFiles || bytes >= limits.maxTotalBytes || now() >= deadline) { limited = true; break; } const absolute = path.join(dir, entry.name), relative = relativeDirectory ? `${relativeDirectory}/${entry.name}` : entry.name;
      if (!relative || relative.startsWith("../") || path.isAbsolute(relative) || entry.isSymbolicLink() || entry.name.includes("\0")) continue;
      if (entry.isDirectory()) { if (!EXCLUDED.has(entry.name) && !SENSITIVE.test(relative)) await walk(absolute, depth + 1,relative); continue; } if (!entry.isFile() || SENSITIVE.test(relative) || BINARY.test(relative)) continue;
      if (platform !== "linux") { notices.push("Repository file excerpts skipped: secure descriptor-target verification is unsupported on this platform."); continue; }
      let handle: nativeFs.FileHandle | undefined; try {
        const expected = await timed("expected target", fs.realpath(absolute)); if (!inside(expected)) throw new Error("outside"); const flags = constants.O_RDONLY | constants.O_NOFOLLOW; const pending = fs.open(absolute, flags); pending.then(h => { if (now() >= deadline && handle !== h) void h.close(); }).catch(() => undefined); handle = await timed("open", pending);
        await timed("descriptor target", assertDescriptorTarget(handle, expected, root, descriptorTarget));
        const before = await timed("fstat", handle.stat()); if (!before.isFile()) throw new Error("not regular");
        const allowance = Math.min(before.size, limits.maxFileBytes, limits.maxTotalBytes - bytes); if (allowance <= 0) { limited = true; break; } const buffer = Buffer.alloc(allowance); const read = await timed("read", handle.read(buffer, 0, allowance, 0)); const after = await timed("verify", handle.stat()); await timed("final descriptor target", assertDescriptorTarget(handle, expected, root, descriptorTarget)); if (before.ino !== after.ino || before.dev !== after.dev) throw new Error("racy replacement");
        if (buffer.subarray(0, read.bytesRead).includes(0)) continue; files++; bytes += read.bytesRead; if (before.size > allowance) limited = true; evidence.push({ path: relative, category: details.has(relative) ? "detail" : category(relative), excerpt: redactSecrets(buffer.subarray(0, read.bytesRead).toString("utf8")) }); details.delete(relative);
      } catch (e: any) { if (e.code === "SPM_TIMEOUT") limited = true; else notices.push("A repository entry became unreadable or changed during discovery."); } finally { await handle?.close().catch(() => undefined); } if (limited && now() >= deadline) break;
    }
  }
  await walk(ioRoot, 0); for (const missing of details) notices.push(`Requested detail path was excluded, missing, or outside discovery limits: ${missing}`); const by = (n: string) => evidence.filter(x => x.category === n).flatMap(x => summary(x.excerpt.split(/\r?\n/))).slice(0, 20), manifests = evidence.filter(x => x.category === "manifest"), docs = evidence.filter(x => x.category === "documentation"), history: string[] = [];
  if (options.allowHistory && options.historyAuthorized && now() < deadline) {
    if (platform !== "linux") notices.push("Git history skipped: secure descriptor-backed repository access is unsupported on this platform.");
    else { let rootFd: nativeFs.FileHandle | undefined, gitFd: nativeFs.FileHandle | undefined; try { rootFd = await timed("pin history root", rootInput instanceof PinnedRepositoryRoot ? rootInput.duplicate() : openPinnedDirectory(root, root, descriptorTarget)); const descriptorRoot = `/proc/${process.pid}/fd/${rootFd.fd}`; const git = path.join(root, ".git"); if (!(rootInput instanceof PinnedRepositoryRoot)) { const gitStat = await timed("git directory", fs.lstat(git)); if (!gitStat.isDirectory() || gitStat.isSymbolicLink() || await timed("git containment", fs.realpath(git)) !== git) throw new Error("unsafe git metadata"); } gitFd = await timed("pin git directory", openPinnedDirectory(`${descriptorRoot}/.git`, root, descriptorTarget, git)); const descriptorGit = `/proc/${process.pid}/fd/${gitFd.fd}`; const timeout = Math.max(1, deadline - now()), env: NodeJS.ProcessEnv = {}; for (const key of ["PATH", "LANG", "LC_ALL"]) if (process.env[key]) env[key] = process.env[key]; const stdout = options.historyRunner ? await timed("git history", options.historyRunner(descriptorRoot, descriptorGit, timeout, env)) : (await timed("git history", exec("git", ["--git-dir", descriptorGit, "--work-tree", descriptorRoot, "log", "-n", "10", "--pretty=format:%h %s", "--no-decorate"], { cwd: "/", env, timeout, maxBuffer: 32000, windowsHide: true }))).stdout; history.push(...redactSecrets(stdout).split(/\r?\n/).filter(Boolean)); } catch (e: any) { notices.push("Git history skipped because secure descriptor-backed containment could not be proven."); if (e.code === "SPM_TIMEOUT") limited = true; } finally { await gitFd?.close().catch(() => undefined); await rootFd?.close().catch(() => undefined); } }
  }
  if (!docs.length) notices.push("No documentation files discovered."); if (!manifests.length) notices.push("No recognized manifest discovered."); if (limited) notices.push("Discovery stopped at a configured resource limit or deadline.");
  return { hostIdentifier: path.basename(root), productPurpose: by("documentation"), existingFunctionality: by("content"), architecture: by("manifest"), terminology: [...new Set(evidence.flatMap(x => x.excerpt.match(/\b[A-Z][A-Za-z]{3,}\b/g) ?? []))].slice(0, 30), documentation: docs.map(x => x.path), uiPatterns: evidence.filter(x => x.category === "ui").map(x => x.path), tests: evidence.filter(x => x.category === "tests").map(x => x.path), conventions: manifests.map(x => x.path), agentConfiguration: evidence.filter(x => x.category === "agent_configuration").map(x => x.path), constraints: limited ? ["Repository context is partial due to configured limits."] : [], evidence, missingContext: [...new Set(notices)], history, containmentGuarantee: platform === "linux" ? "linux-descriptor-target-verified" : "unsupported-content-skipped" };
}
