import { mkdir, symlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { discoverRepository } from "../../../src/repository/index.js";
import { copyFixture,fixturesRoot,treeHash } from "../../support/core/helpers.js";
const linux=process.platform==="linux"?it:it.skip;
describe("V-09/V-11 portable fixture discovery",()=>{
 linux.each(["web-catalog","python-weather","go-renamer","minimal"])("normalizes %s without changing original bytes",async name=>{const original=path.join(fixturesRoot,name),before=await treeHash(original),copy=await copyFixture(name),copyBefore=await treeHash(copy);const context=await discoverRepository(copy);expect(await treeHash(original)).toBe(before);expect(await treeHash(copy)).toBe(copyBefore);expect(context.evidence.length).toBeGreaterThan(0);expect(context.containmentGuarantee).toBe("linux-descriptor-target-verified");if(name==="web-catalog"){expect(context.productPurpose.join(" ")).toMatch(/catalog/i);expect(context.documentation).toContain("README.md");expect(context.uiPatterns.some(x=>x.includes("components")||x.includes("public"))).toBe(true);expect(context.tests.some(x=>x.includes("test"))).toBe(true);expect(context.conventions).toContain("package.json");expect(context.agentConfiguration).toContain("AGENTS.md");}if(name==="python-weather")expect(context.architecture.join(" ")).toMatch(/weather-station-api/i);if(name==="go-renamer")expect(context.existingFunctionality.join(" ")).toMatch(/package|preview|command/i);if(name==="minimal")expect(context.missingContext).toEqual(expect.arrayContaining(["No documentation files discovered.","No recognized manifest discovered."]));});
 linux("excludes sensitive, vendor, generated, binary, symlink, and outside bytes",async()=>{const copy=await copyFixture("web-catalog"),outside=await copyFixture("minimal");await mkdir(path.join(copy,"node_modules/pkg"),{recursive:true});await writeFile(path.join(copy,"node_modules/pkg/index.js"),"vendor-marker");await mkdir(path.join(copy,"dist"));await writeFile(path.join(copy,"dist/generated.js"),"generated-marker");await writeFile(path.join(copy,".env"),"TOKEN=fixture-placeholder");await writeFile(path.join(copy,"image.png"),Buffer.from([0,1,2,3]));await symlink(path.join(outside,"notes.txt"),path.join(copy,"outside-link.txt"));const serialized=JSON.stringify(await discoverRepository(copy));for(const forbidden of ["vendor-marker","generated-marker","fixture-placeholder","Scratch repository"])expect(serialized).not.toContain(forbidden);});
 it("skips excerpts honestly off Linux",async()=>{const context=await discoverRepository(path.join(fixturesRoot,"web-catalog"),{platform:"darwin"});expect(context.evidence).toEqual([]);expect(context.containmentGuarantee).toBe("unsupported-content-skipped");});
});
