import { execFile } from "node:child_process";
import { mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { describe,expect,it } from "vitest";
import { PinnedRepositoryRoot } from "../../../src/shared/secure-fs.js";
import { inspectApprovalSidecar, writeRevision } from "../../../src/spec/writer.js";
import { validateArtifactSet } from "../../../src/validation/artifacts.js";
import { productContentHash } from "../../../src/validation/validate.js";
import { canonicalInput,copyFixture,fixturesRoot,treeHash } from "../../support/core/helpers.js";
const run=promisify(execFile),linux=process.platform==="linux"?it:it.skip,support=path.resolve(import.meta.dirname,"../../support/core");
async function child(script:string,args:string[],input:unknown,env:Record<string,string>={}){try{return await run(process.execPath,[path.join(support,script),...args],{env:{...process.env,...env,SPEC_INPUT:JSON.stringify(input)},maxBuffer:1_000_000});}catch(error:any){return{stdout:error.stdout??"",stderr:error.stderr??""};}}
describe("V-06/V-09 process-level core",()=>{
 linux("copies only tracked fixture content",async()=>{const source=path.join(fixturesRoot,"web-catalog"),probe=path.join(source,".opencode/untracked-copy-probe.json");await mkdir(path.dirname(probe),{recursive:true});await writeFile(probe,"untracked fixture data");let copy="";try{copy=await copyFixture("web-catalog");await expect(readFile(path.join(copy,".opencode/untracked-copy-probe.json"))).rejects.toThrow();}finally{await rm(probe,{force:true});if(copy)await rm(copy,{recursive:true,force:true});}});
 linux("renders byte-identically across timezone and locale-like environments",async()=>{const copy=await copyFixture("python-weather"),input=canonicalInput(path.basename(copy)),outputs=[] as string[];for(const [i,env] of [{TZ:"UTC",LANG:"C"},{TZ:"Pacific/Honolulu",LANG:"tr_TR.UTF-8"},{TZ:"Asia/Tokyo",LC_ALL:"de_DE.UTF-8"}].entries()){const out=path.join(copy,`render-${i}.json`);await child("process-render.mjs",[out],input,env);outputs.push(await readFile(out,"utf8"));}expect(new Set(outputs).size).toBe(1);});
 linux("allows exactly one committed winner in simultaneous clean-root processes",async()=>{const copy=await copyFixture("go-renamer"),input=canonicalInput(path.basename(copy)),before=await treeHash(copy,true),results=await Promise.all([child("process-publish.mjs",[copy],input),child("process-publish.mjs",[copy],input)]),parsed=results.map(x=>JSON.parse(x.stdout));expect(parsed.filter(x=>x.ok)).toHaveLength(1);expect(parsed.filter(x=>!x.ok)).toHaveLength(1);expect(await treeHash(copy,true)).toBe(before);const root=path.join(copy,".opencode/specs/senior-pm"),files=await readdir(root);expect(files.filter(x=>x.endsWith(".manifest.json"))).toEqual(["portable-checkpoint.r001.manifest.json"]);expect((await validateArtifactSet(copy,".opencode/specs/senior-pm","portable-checkpoint.r001")).valid).toBe(true);expect(files.some(x=>/\.(rb|py|go|js|ts|html)$/.test(x))).toBe(false);});
 linux("fails closed after root replacement following descriptor pin",async()=>{const copy=await copyFixture("minimal"),pinned=await PinnedRepositoryRoot.open(copy),moved=`${copy}-moved`;await rename(copy,moved);await mkdir(copy);try{await expect(writeRevision(pinned,canonicalInput(path.basename(moved)))).rejects.toThrow();expect(await readdir(copy)).toEqual([]);}finally{await pinned.close();await rm(copy,{recursive:true,force:true});await rename(moved,copy);}});
 linux("rejects stale/forged approval and current policy tightening",async()=>{const copy=await copyFixture("web-catalog"),boot=canonicalInput(path.basename(copy));boot.slug="bootstrap";boot.specId="BOOT";await writeRevision(copy,boot);const input=canonicalInput(path.basename(copy));input.interfaceImpact="minor_interaction";await writeFile(path.join(copy,".opencode/specs/senior-pm/review.json"),JSON.stringify({schemaVersion:"1.0.0",specId:input.specId,revision:1,productContentHash:"0".repeat(64),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"fixture review"}));const inspected=await inspectApprovalSidecar(copy,".opencode/specs/senior-pm","review.json");await expect(writeRevision(copy,input,{approvalSidecar:"review.json",expectedApprovalSha256:inspected.sha256})).rejects.toThrow();input.interfaceImpact="none";const ready=await writeRevision(copy,input);const tightened=await validateArtifactSet(copy,ready.outputRoot,ready.base,{currentPolicy:{additionalNonGoals:["No exports"],requiredAdditionalSections:["security-notes"]}});expect(tightened).toMatchObject({valid:false,handoffEligible:false,revisionRequired:true});expect(tightened.failures.join(" ")).toContain("policy_outdated");});
 linux("preserves host-owned .opencode bytes through publication and policy validation",async()=>{const copy=await copyFixture("web-catalog"),sentinel=path.join(copy,".opencode/host-settings.json"),bytes=Buffer.concat([Buffer.from('{"theme":"host-owned","fixture":true}'),Buffer.from([10])]);await mkdir(path.dirname(sentinel),{recursive:true});await writeFile(sentinel,bytes);const before=await treeHash(copy,true),input=canonicalInput(path.basename(copy)),written=await writeRevision(copy,input);await validateArtifactSet(copy,written.outputRoot,written.base,{currentPolicy:{additionalNonGoals:["No newly required goal"]}});expect(await readFile(sentinel)).toEqual(bytes);expect(await treeHash(copy,true)).toBe(before);});
 linux("confinement hash detects host .opencode mutations but excludes only owned spec changes",async()=>{const copy=await copyFixture("web-catalog"),before=await treeHash(copy,true),owned=path.join(copy,".opencode/specs/senior-pm");await mkdir(owned,{recursive:true});await writeFile(path.join(owned,"ignored.txt"),"owned change");expect(await treeHash(copy,true)).toBe(before);await writeFile(path.join(copy,".opencode/host-settings.json"),'{"theme":"changed"}\n');expect(await treeHash(copy,true)).not.toBe(before);});
 linux("writes only the copied fixture owned root with labels, additions, and non-goals",async()=>{const original=path.join(fixturesRoot,"minimal"),originalHash=await treeHash(original),copy=await copyFixture("minimal"),before=await treeHash(copy,true),input=canonicalInput(path.basename(copy)),result=await writeRevision(copy,input,{policy:{additionalNonGoals:["No production source files are modified."],requiredAdditionalSections:["integration-notes"]}});expect(await treeHash(original)).toBe(originalHash);expect(await treeHash(copy,true)).toBe(before);expect(result.rendered.markdown).toMatch(/Facts|Inferences|Assumptions|Unresolved/);expect(result.rendered.markdown).toContain("No production source files are modified.");expect(result.rendered.markdown).toContain("## 24. Integration notes");});
});
