import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
export const packageRoot=path.resolve(import.meta.dirname,"../../..");
export async function temporary(prefix="spm-runtime-"){return mkdtemp(path.join(os.tmpdir(),prefix));}
export function spec(revision=1){return {schemaVersion:"1.0.0",pluginVersion:"0.1.0",specId:"SPEC-NEUTRAL",slug:"neutral-workflow",revision,generatedAt:"2026-07-18T12:00:00.000Z",title:"Recover interrupted work",hostIdentifier:"neutral-host",requestedBy:"owner",pm:{agent:"senior-pm"},executiveSummary:"Recover interrupted work safely.",repositoryContext:"The repository contains a bounded workflow.",targetUser:"Operators",userProblem:"Interrupted work loses progress.",desiredOutcome:"Operators resume without duplicate effects.",proposedSolution:"Record resumable checkpoints.",smallestShippableSlice:"Resume one interrupted operation.",userStories:["As an operator, I resume work."],functionalRequirements:[{id:"FR-001",text:"Record a checkpoint"}],acceptanceCriteria:[{id:"AC-001",requirementIds:["FR-001"],behavior:"Given an interruption, when resumed, then the system records one checkpoint"}],uxExpectations:"Show the recorded checkpoint.",businessRules:["One active operation"],edgeCases:["Duplicate resume"],nonFunctionalExpectations:["Do not expose private data"],existingBehaviorToPreserve:["Completed operations remain unchanged"],nonGoals:["Billing"],futureConsiderations:["Multiple checkpoints"],dependenciesAndConstraints:["Existing storage"],definitionOfDone:[{text:"AC-001 passes",acceptanceCriteria:["AC-001"]}],handoffInstructions:"Use FR and AC identifiers during planning.",evidence:{facts:[],inferences:[],assumptions:[],unresolved:[]},interfaceImpact:"none",technicalPlanningRequired:true};}
export const context=(root:string,ask=async(_input:any)=>{})=>({sessionID:"parent",messageID:"message",agent:"senior-pm",directory:root,worktree:root,abort:new AbortController().signal,metadata(){},ask});
export async function cleanEnvironment(root:string){const home=path.join(root,"home"),config=path.join(root,"config");await mkdir(home);await mkdir(config);return {HOME:home,XDG_CONFIG_HOME:config,OPENCODE_CONFIG_DIR:path.join(config,"opencode")};}
export async function operatorConfig(env:Record<string,string>,settings:Record<string,unknown>){const root=env.XDG_CONFIG_HOME;if(!root)throw new Error("XDG_CONFIG_HOME is required");const dir=path.join(root,"opencode");await mkdir(dir,{recursive:true});await writeFile(path.join(dir,"senior-pm.json"),JSON.stringify({senior_pm:settings}));}
