import { constants } from "node:fs";
import { open, unlink, type FileHandle } from "node:fs/promises";
import path from "node:path";
import { OWNED_SPECIFICATION_DIRECTORY } from "../shared/constants.js";
import { ACCEPTED_OWNERSHIP_MARKERS, OWNERSHIP_MARKER } from "../shared/constants.js";
import { assertDescriptorTarget, fdChild, mkdirPinnedChild, openPinnedDirectory, openPinnedRegular, PinnedRepositoryRoot, repositoryCanonicalPath, type DescriptorResolver, type RepositoryRoot } from "../shared/secure-fs.js";
import { validateArtifactSet, type PriorArtifactReference } from "../validation/artifacts.js";
import { evaluateSpecInternal } from "../validation/validate.js";
import type { EvaluationPolicy, ProductSpecInput, SpecStatus } from "./contract.js";
import { deterministicJson, sha256 } from "./normalize.js";
import { validateOutputRoot } from "./output-root.js";
import { artifactManifest, renderSpec } from "./render.js";
const OWNER = ".senior-pm-owned.json";
export { validateOutputRoot } from "./output-root.js";
async function writeExclusive(dir: FileHandle, name: string, expected: string, repo: string, content: string, resolver?: DescriptorResolver) { const handle = await open(fdChild(dir, name), constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600); try { await assertDescriptorTarget(handle, expected, repo, resolver); await handle.writeFile(content); await handle.sync(); } finally { await handle.close(); } }
async function pinnedOwnedRoot(repositoryRoot:RepositoryRoot,repo: string, relative: string, resolver?: DescriptorResolver) {
  if (process.platform !== "linux") throw new Error("Secure publication requires Linux descriptor-target verification");
  const repoFd = repositoryRoot instanceof PinnedRepositoryRoot ? await repositoryRoot.duplicate() : await openPinnedDirectory(repositoryRoot.startsWith("/proc/")?repositoryRoot:repo, repo, resolver,repo); let current = repoFd, expected = repo, createdFinal = false;
  try { for (const part of relative.split(path.sep)) { const next = path.join(expected, part); let child: FileHandle; try { child = await openPinnedDirectory(fdChild(current, part), repo, resolver, next); } catch (error: any) { if (error.code !== "ENOENT") throw error; await mkdirPinnedChild(current, part); child = await openPinnedDirectory(fdChild(current, part), repo, resolver, next); if (part === "senior-pm") createdFinal = true; } if (current !== repoFd) await current.close(); current = child; expected = next; }
    if (createdFinal) await writeExclusive(current, OWNER, path.join(expected, OWNER), repo, OWNERSHIP_MARKER, resolver);
    const marker = await openPinnedRegular(current, OWNER, path.join(expected, OWNER), repo, constants.O_RDONLY, resolver); try { if (!ACCEPTED_OWNERSHIP_MARKERS.has(await marker.readFile("utf8"))) throw new Error("Invalid ownership marker"); } finally { await marker.close(); }
    return { repoFd, rootFd: current, root: expected };
  } catch (error) { if (current !== repoFd) await current.close().catch(() => undefined); await repoFd.close().catch(() => undefined); throw error; }
}
async function rollback(dir: FileHandle, name: string, expected: string, repo: string, hash: string, resolver?: DescriptorResolver) { try { const handle = await openPinnedRegular(dir, name, expected, repo, constants.O_RDONLY, resolver); try { if (sha256(await handle.readFile()) !== hash) return; } finally { await handle.close(); } await unlink(fdChild(dir, name)); } catch { /* suspicious partial remains uncommitted */ } }
async function readExternalSidecar(rootFd: FileHandle, root: string, repo: string, relative: string, resolver?: DescriptorResolver) { const normalized = relative.replace(/\\/g,"/"), parts = normalized.split("/"); if (!normalized || path.posix.isAbsolute(normalized) || parts.some(x=>!x||x==="."||x==="..") || !normalized.endsWith(".json")) throw new Error("Approval sidecar must be a safe relative JSON path under the owned output root"); let current=rootFd, expected=root; try { for(const part of parts.slice(0,-1)){const next=path.join(expected,part),child=await openPinnedDirectory(fdChild(current,part),repo,resolver,next);if(current!==rootFd)await current.close();current=child;expected=next;}const name=parts.at(-1)!,handle=await openPinnedRegular(current,name,path.join(expected,name),repo,constants.O_RDONLY,resolver);try{const stat=await handle.stat();if(stat.size>64_000)throw new Error("Approval sidecar exceeds 64000 bytes");return await handle.readFile("utf8");}finally{await handle.close();}}finally{if(current!==rootFd)await current.close().catch(()=>undefined);} }
export async function inspectApprovalSidecar(repositoryRoot:RepositoryRoot,outputRoot:string,approvalSidecar:string,descriptorTarget?:DescriptorResolver){const repo=await repositoryCanonicalPath(repositoryRoot),relative=validateOutputRoot(outputRoot),repoFd=repositoryRoot instanceof PinnedRepositoryRoot?await repositoryRoot.duplicate():await openPinnedDirectory(repo,repo,descriptorTarget);let rootFd=repoFd,expected=repo;try{for(const part of relative.split(path.sep)){expected=path.join(expected,part);const next=await openPinnedDirectory(fdChild(rootFd,part),repo,descriptorTarget,expected);if(rootFd!==repoFd)await rootFd.close();rootFd=next;}const bytes=await readExternalSidecar(rootFd,expected,repo,approvalSidecar,descriptorTarget),parsed=(await import("../validation/schemas.js")).designApprovalSchema.safeParse(JSON.parse(bytes));if(!parsed.success)throw new Error("Approval sidecar schema invalid");return{path:approvalSidecar.replace(/\\/g,"/"),sha256:sha256(bytes),identity:{specId:parsed.data.specId,revision:parsed.data.revision,productContentHash:parsed.data.productContentHash,reviewer:parsed.data.reviewer,evidence:parsed.data.evidence}};}finally{if(rootFd!==repoFd)await rootFd.close();await repoFd.close();}}
export interface WriteRevisionOptions { outputRoot?: string; approvalSidecar?: string; expectedApprovalSha256?: string; faultAfterFiles?: number; descriptorTarget?: DescriptorResolver; priorArtifact?: PriorArtifactReference; policy?: EvaluationPolicy }
export async function writeRevision(repoRoot: RepositoryRoot, input: ProductSpecInput, options: WriteRevisionOptions | string = {}) {
  const opts = typeof options === "string" ? { outputRoot: options } : options, repo = await repositoryCanonicalPath(repoRoot), outputRelative = validateOutputRoot(opts.outputRoot); if(!!opts.approvalSidecar!==!!opts.expectedApprovalSha256)throw new Error("Approval sidecar and expected digest are both required");
  if (!Number.isInteger(input.revision) || input.revision < 1) throw new Error("Invalid revision"); let validatedPriorStatus: SpecStatus | undefined;
  if (opts.priorArtifact) { const priorRepo = await repositoryCanonicalPath(opts.priorArtifact.repositoryRoot).catch(() => ""), priorOutput = validateOutputRoot(opts.priorArtifact.outputRoot); if (priorRepo !== repo || priorOutput !== outputRelative) throw new Error("Prior artifact repository/output root does not match"); const prior = await validateArtifactSet(opts.priorArtifact.repositoryRoot, priorOutput, opts.priorArtifact.base, { descriptorTarget: opts.descriptorTarget }); if (!prior.valid || !prior.spec || prior.spec.specId !== input.specId || prior.spec.slug !== input.slug || prior.spec.hostIdentifier !== input.hostIdentifier || prior.spec.revision >= input.revision) throw new Error("Prior artifact is invalid or not from the same spec lineage"); validatedPriorStatus = prior.spec.status; }
  const pinned = await pinnedOwnedRoot(repoRoot,repo, outputRelative, opts.descriptorTarget);
  try { let approvalBytes=opts.approvalSidecar?await readExternalSidecar(pinned.rootFd,pinned.root,repo,opts.approvalSidecar,opts.descriptorTarget):undefined;if(approvalBytes&&sha256(approvalBytes)!==opts.expectedApprovalSha256)throw new Error("Approval sidecar digest mismatch"); const spec = evaluateSpecInternal(input, approvalBytes, { validatedPriorStatus },opts.policy), rendered = renderSpec(spec), base = `${input.slug}.r${String(input.revision).padStart(3, "0")}`, reviewName=approvalBytes?`${base}.design-review.json`:undefined, priorName=opts.priorArtifact?`${base}.prior-artifact.json`:undefined, priorBytes=opts.priorArtifact?deterministicJson({schemaVersion:"1.0.0",specId:input.specId,slug:input.slug,hostIdentifier:input.hostIdentifier,revision:Number(opts.priorArtifact.base.match(/\.r(\d+)$/)?.[1]??"0"),base:opts.priorArtifact.base}):undefined, persisted={...(reviewName&&approvalBytes?{designReview:{file:reviewName,sha256:sha256(approvalBytes)}}:{}),...(priorName&&priorBytes?{priorArtifact:{file:priorName,sha256:sha256(priorBytes)}}:{})}, manifest = artifactManifest(spec, rendered,persisted), claimName = `${base}.claim`, claim = `${spec.productContentHash}\n`, created: Array<[string, string]> = [];
    await writeExclusive(pinned.rootFd, claimName, path.join(pinned.root, claimName), repo, claim, opts.descriptorTarget); created.push([claimName, sha256(claim)]); const data: Array<[string, string]> = [[`${base}.json`, rendered.canonicalJson], [`${base}.md`, rendered.markdown], [`${base}.handoff.json`, rendered.handoffJson],...(reviewName&&approvalBytes?[[reviewName,approvalBytes] as [string,string]]:[]),...(priorName&&priorBytes?[[priorName,priorBytes] as [string,string]]:[])];
    try { for (const [name, content] of data) { await assertDescriptorTarget(pinned.rootFd, pinned.root, repo, opts.descriptorTarget); await writeExclusive(pinned.rootFd, name, path.join(pinned.root, name), repo, content, opts.descriptorTarget); created.push([name, sha256(content)]); if (opts.faultAfterFiles === created.length - 1) throw new Error("Injected publication interruption"); } const manifestName = `${base}.manifest.json`; await writeExclusive(pinned.rootFd, manifestName, path.join(pinned.root, manifestName), repo, manifest, opts.descriptorTarget); return { root: pinned.root, outputRoot: outputRelative, base, spec, rendered, manifest, paths: [...data.map(x => path.join(pinned.root, x[0])), path.join(pinned.root, manifestName)] }; }
    catch (error) { for (const [name, hash] of created.reverse()) await rollback(pinned.rootFd, name, path.join(pinned.root, name), repo, hash, opts.descriptorTarget); throw error; }
  } finally { await pinned.rootFd.close().catch(() => undefined); await pinned.repoFd.close().catch(() => undefined); }
}
