import { mkdtemp, mkdir, readFile, symlink, writeFile } from "node:fs/promises"; import os from "node:os"; import path from "node:path"; import { describe, expect, it } from "vitest";
import { SECTION_TITLES } from "../../../src/spec/contract.js"; import { renderSpec } from "../../../src/spec/render.js"; import { inspectApprovalSidecar, validateOutputRoot, writeRevision as coreWriteRevision, type WriteRevisionOptions } from "../../../src/spec/writer.js"; import { validateArtifactSet } from "../../../src/validation/artifacts.js"; import { evaluateSpec } from "../../../src/validation/validate.js"; import { specFixture } from "./fixture.js";
import { LEGACY_OWNERSHIP_MARKER, OWNERSHIP_MARKER } from "../../../src/shared/constants.js";
async function writeRevision(repo:string,input:Parameters<typeof coreWriteRevision>[1],options:WriteRevisionOptions|string={}){if(typeof options!=="string"&&options.approvalSidecar&&!options.expectedApprovalSha256){const inspection=await inspectApprovalSidecar(repo,options.outputRoot??".opencode/specs/senior-pm",options.approvalSidecar);options={...options,expectedApprovalSha256:inspection.sha256};}return coreWriteRevision(repo,input,options);}
describe("authoritative canonical rendering", () => {
  it("generates all 23 sections, title, status, FR, AC, evidence and non-goals from one structure", () => { const s = evaluateSpec(specFixture()), r = renderSpec(s); expect([...r.markdown.matchAll(/^## \d+\. (.+)$/gm)].map(x => x[1])).toEqual(SECTION_TITLES); expect(r.markdown).toContain("# Interrupt recovery"); expect(r.markdown).toContain("FR-001"); expect(r.markdown).toContain("AC-001"); expect(r.markdown).toContain("Assumptions"); expect(r.markdown).toContain("Billing"); expect(r.handoffJson).toContain(s.status); });
  it("is deterministic across process locale/timezone values", () => { const input = specFixture(), a = renderSpec(evaluateSpec(input)), tz=process.env.TZ,lang=process.env.LANG; try{process.env.TZ = "Pacific/Honolulu"; process.env.LANG = "tr_TR.UTF-8"; expect(renderSpec(evaluateSpec(input))).toEqual(a);}finally{if(tz===undefined)delete process.env.TZ;else process.env.TZ=tz;if(lang===undefined)delete process.env.LANG;else process.env.LANG=lang;} });
});
describe("owned manifest-last immutable publication", () => {
  it.each(["../senior-pm", "/tmp/senior-pm", "C:\\tmp\\senior-pm", "\\\\server\\share\\senior-pm", "src/senior-pm", "config/senior-pm", ".opencode/specs/senior-pm.json"])("rejects %s", x => expect(() => validateOutputRoot(x)).toThrow());
  it("never adopts an existing unowned root", async () => { const repo = await mkdtemp(path.join(os.tmpdir(), "spm-unowned-")); await mkdir(path.join(repo, ".opencode/specs/senior-pm"), { recursive: true }); await expect(writeRevision(repo, specFixture())).rejects.toThrow(/ENOENT|ownership|owned/i); });
  it("writes only the neutral marker for a new root",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-neutral-owner-")),out=await writeRevision(repo,specFixture());expect(await readFile(path.join(out.root,".senior-pm-owned.json"),"utf8")).toBe(OWNERSHIP_MARKER);});
  it("accepts exactly neutral and frozen legacy markers while preserving legacy roots",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-owner-dual-")),root=path.join(repo,".opencode/specs/senior-pm");await mkdir(root,{recursive:true});await writeFile(path.join(root,".senior-pm-owned.json"),LEGACY_OWNERSHIP_MARKER);const out=await writeRevision(repo,specFixture());expect(await readFile(path.join(root,".senior-pm-owned.json"),"utf8")).toBe(LEGACY_OWNERSHIP_MARKER);expect((await validateArtifactSet(repo,out.outputRoot,out.base)).valid).toBe(true);for(const rejected of ["",OWNERSHIP_MARKER.trim(),'{"owner":"senior-pm.plugin ","schemaVersion":"1.0.0"}\n','{"owner":["senior-pm.plugin","elon-musk-agents.senior-product-manager"],"schemaVersion":"1.0.0"}\n']){await writeFile(path.join(root,".senior-pm-owned.json"),rejected);expect((await validateArtifactSet(repo,out.outputRoot,out.base)).valid).toBe(false);}await writeFile(path.join(root,".senior-pm-owned.json"),OWNERSHIP_MARKER);expect((await validateArtifactSet(repo,out.outputRoot,out.base)).valid).toBe(true);});
  it("has exactly one complete winner on a simultaneous clean-root start", async () => { const repo = await mkdtemp(path.join(os.tmpdir(), "spm-race-")); const settled = await Promise.allSettled([writeRevision(repo, specFixture()), writeRevision(repo, specFixture())]); expect(settled.filter(x => x.status === "fulfilled")).toHaveLength(1); expect(settled.filter(x => x.status === "rejected")).toHaveLength(1); const winner = settled.find(x => x.status === "fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof writeRevision>>>; expect((await validateArtifactSet(repo, winner.value.outputRoot, winner.value.base)).valid).toBe(true); });
  it("publishes draft failures authoritatively and rejects forged sidecars", async () => { const repo = await mkdtemp(path.join(os.tmpdir(), "spm-draft-")), input = specFixture(); input.userProblem = ""; const out = await writeRevision(repo, input); expect(out.spec.status).toBe("Draft"); expect(out.spec.validationFailures.length).toBeGreaterThan(0); expect((await validateArtifactSet(repo, out.outputRoot, out.base)).valid).toBe(true); await writeFile(path.join(out.root, `${out.base}.handoff.json`), "{}\n"); expect((await validateArtifactSet(repo, out.outputRoot, out.base)).valid).toBe(false); });
  it("leaves interrupted sets uncommitted and rolls back owned files", async () => { const repo = await mkdtemp(path.join(os.tmpdir(), "spm-stop-")); await expect(writeRevision(repo, specFixture(), { faultAfterFiles: 1 })).rejects.toThrow(/interruption/); expect((await validateArtifactSet(repo, ".opencode/specs/senior-pm", "sample.r001")).valid).toBe(false); });
  it("rejects symlink output components", async () => { const repo = await mkdtemp(path.join(os.tmpdir(), "spm-link-")), outside = await mkdtemp(path.join(os.tmpdir(), "outside-")); await symlink(outside, path.join(repo, ".opencode")); await expect(writeRevision(repo, specFixture())).rejects.toThrow(/ENOTDIR|symlink/i); });
  it("fails before publication when a pinned descriptor target mismatches",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-fd-"));await expect(writeRevision(repo,specFixture(),{descriptorTarget:async()=>"/tmp/outside"})).rejects.toThrow(/descriptor target mismatch/);});
  it("supports arbitrary positive revision widths",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-rev-")),input=specFixture();input.revision=1000;const out=await writeRevision(repo,input);expect(out.base).toBe("sample.r1000");const checked=await validateArtifactSet(repo,out.outputRoot,out.base);expect(checked,checked.failures.join("; ")).toMatchObject({valid:true});});
  it("validates explicit default and custom roots without .opencode inference",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"contains-.opencode-parent-")),input=specFixture();const custom=await writeRevision(repo,input,{outputRoot:"specs/senior-pm"});expect((await validateArtifactSet(repo,"specs/senior-pm",custom.base)).valid).toBe(true);expect((await validateArtifactSet(repo,".opencode/specs/senior-pm",custom.base)).valid).toBe(false);const other=await mkdtemp(path.join(os.tmpdir(),"wrong-repo-"));expect((await validateArtifactSet(other,"specs/senior-pm",custom.base)).valid).toBe(false);expect((await validateArtifactSet(repo,"../senior-pm",custom.base)).valid).toBe(false);});
  it("persists external approval and replays approved and returned-prior state",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-prior-")),bootstrap=specFixture();bootstrap.slug="bootstrap";bootstrap.specId="BOOT";await writeRevision(repo,bootstrap);const first=specFixture();first.interfaceImpact="substantial_ui";const approval={schemaVersion:"1.0.0",specId:first.specId,revision:1,productContentHash:(await import("../../../src/validation/validate.js")).productContentHash(first),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review"};await mkdir(path.join(repo,".opencode/specs/senior-pm/approvals"));await writeFile(path.join(repo,".opencode/specs/senior-pm/approvals/review.json"),JSON.stringify(approval));const prior=await writeRevision(repo,first,{approvalSidecar:"approvals/review.json"});expect(prior.spec.status).toBe("Ready for technical planning");expect((await validateArtifactSet(repo,prior.outputRoot,prior.base)).valid).toBe(true);const second=specFixture();second.revision=2;second.userProblem="";const reference={repositoryRoot:repo,outputRoot:prior.outputRoot,base:prior.base};const revised=await writeRevision(repo,second,{priorArtifact:reference});expect(revised.spec.status).toBe("Returned for product revision");expect((await validateArtifactSet(repo,revised.outputRoot,revised.base)).valid).toBe(true);await writeFile(path.join(repo,".opencode/specs/senior-pm",`${prior.base}.design-review.json`),"{}");expect((await validateArtifactSet(repo,prior.outputRoot,prior.base)).valid).toBe(false);});
  it("rejects prior artifacts from a wrong repo, output, slug, host, spec or non-lower revision",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-lineage-")),prior=await writeRevision(repo,specFixture()),baseRef={repositoryRoot:repo,outputRoot:prior.outputRoot,base:prior.base};const other=await mkdtemp(path.join(os.tmpdir(),"spm-other-"));const cases=[{repositoryRoot:other,outputRoot:prior.outputRoot,base:prior.base},{repositoryRoot:repo,outputRoot:"specs/senior-pm",base:prior.base}];for(const ref of cases){const next=specFixture();next.revision=2;await expect(writeRevision(repo,next,{priorArtifact:ref})).rejects.toThrow();}for(const mutate of [(x:any)=>x.slug="other",(x:any)=>x.hostIdentifier="other-host",(x:any)=>x.specId="OTHER",(x:any)=>x.revision=1]){const next=specFixture();mutate(next);await expect(writeRevision(repo,next,{priorArtifact:baseRef})).rejects.toThrow(/lineage|precede|invalid/i);}});
  it("rejects forbidden output segments anywhere",()=>{for(const root of ["safe/src/nested/senior-pm","safe/public/senior-pm","safe/vendor/senior-pm","safe/build/senior-pm","safe/runtime/senior-pm","safe/.opencode/senior-pm"])expect(()=>validateOutputRoot(root)).toThrow(/forbidden/);});
  it("escapes heading/control injection and preserves exact declared heading order",()=>{const input=specFixture();input.title="Safe\n# forged";input.userProblem="Problem\n## 99. Status\u0000";input.additionalSections=[{id:"audit",title:"Audit\n## forged",body:"# injected\nEvidence"}];const markdown=renderSpec(evaluateSpec(input)).markdown,headings=markdown.match(/^#{1,2} .+$/gm)??[];expect(headings).toHaveLength(25);expect(headings[0]).toBe("# Safe \\# forged");expect(headings.at(-1)).toBe("## 24. Audit \\#\# forged");expect(markdown).not.toContain("\u0000");});
  it("accepts external sidecar references only and rejects missing/self review",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-review-")),bootstrap=specFixture();bootstrap.slug="boot";bootstrap.specId="BOOT";await writeRevision(repo,bootstrap);const input=specFixture();input.interfaceImpact="minor_interaction";await expect(writeRevision(repo,input,{approvalSidecar:"missing.json"})).rejects.toThrow();const self={schemaVersion:"1.0.0",specId:input.specId,revision:1,productContentHash:(await import("../../../src/validation/validate.js")).productContentHash(input),decision:"approved",reviewer:{id:"senior-pm",name:"PM"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"self"};await writeFile(path.join(repo,".opencode/specs/senior-pm/self.json"),JSON.stringify(self));await expect(writeRevision(repo,input,{approvalSidecar:"self.json"})).rejects.toThrow(/self-approved/);});
  it("fails replay when persisted prior metadata is tampered or missing",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-prior-tamper-")),prior=await writeRevision(repo,specFixture()),next=specFixture();next.revision=2;next.userProblem="";const revised=await writeRevision(repo,next,{priorArtifact:{repositoryRoot:repo,outputRoot:prior.outputRoot,base:prior.base}});await writeFile(path.join(revised.root,`${revised.base}.prior-artifact.json`),"{}\n");expect((await validateArtifactSet(repo,revised.outputRoot,revised.base)).valid).toBe(false);});
  it("refuses ready historical artifacts under newly tightened policy without broadening weaker policy",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-policy-")),out=await writeRevision(repo,specFixture());expect((await validateArtifactSet(repo,out.outputRoot,out.base,{currentPolicy:{}})).valid).toBe(true);const tightened=await validateArtifactSet(repo,out.outputRoot,out.base,{currentPolicy:{additionalNonGoals:["No exports"],requiredAdditionalSections:["audit"]}});expect(tightened).toMatchObject({valid:false,handoffEligible:false,revisionRequired:true});expect(tightened.failures.join(" ")).toContain("policy_outdated");});
  it("binds approval authorization to inspected path and exact digest",async()=>{const repo=await mkdtemp(path.join(os.tmpdir(),"spm-review-race-")),boot=specFixture();boot.slug="boot";await writeRevision(repo,boot);const input=specFixture();input.interfaceImpact="minor_interaction";const approval={schemaVersion:"1.0.0",specId:input.specId,revision:1,productContentHash:(await import("../../../src/validation/validate.js")).productContentHash(input),decision:"approved",reviewer:{id:"designer",name:"Designer"},reviewedAt:"2026-07-18T13:00:00.000Z",evidence:"review"},file=path.join(repo,".opencode/specs/senior-pm/review.json");await writeFile(file,JSON.stringify(approval));const inspected=await inspectApprovalSidecar(repo,".opencode/specs/senior-pm","review.json");expect(inspected.identity.specId).toBe(input.specId);await writeFile(file,JSON.stringify({...approval,evidence:"replaced"}));await expect(coreWriteRevision(repo,input,{approvalSidecar:"review.json",expectedApprovalSha256:inspected.sha256})).rejects.toThrow(/digest mismatch/);});
});
